# Code generated by tabletheory gen --lang py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from theorydb_py import ModelDefinition, Projection, WritePolicy, gsi, theorydb_field


@dataclass(frozen=True)
class DMSNote:
    pk: str = theorydb_field(name="PK", roles=["pk"])
    sk: str = theorydb_field(name="SK", roles=["sk"])
    title: str = theorydb_field(name="title", omitempty=True, default="")
    count: int = theorydb_field(name="count", default=0)
    tags: set[str] = theorydb_field(name="tags", omitempty=True, set_=True, default_factory=set)
    payload: dict[str, Any] = theorydb_field(name="payload", json=True, default_factory=dict)
    blob: bytes = theorydb_field(name="blob", binary=True, default=b"")
    secret: str = theorydb_field(name="secret", omitempty=True, encrypted=True, default="")
    created_at: str = theorydb_field(name="createdAt", roles=["created_at"], default="")
    version: int = theorydb_field(name="version", roles=["version"], default=0)
    ttl: int = theorydb_field(name="ttl", roles=["ttl"], omitempty=True, default=0)


DMSNoteDefinition = ModelDefinition.from_dataclass(
    DMSNote,
    table_name="dms_notes",
    write_policy=WritePolicy(mode="mutable", protected_attributes=("title",)),
    indexes=[
        gsi(
            "gsi-title",
            partition="title",
            sort="created_at",
            projection=Projection.include("count", "payload"),
        ),
    ],
)
