// Code generated by tabletheory gen --cdk; DO NOT EDIT.
import type { Construct } from 'constructs';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';

export type DMSNoteTableOptions = Partial<dynamodb.TableProps>;

export function createDMSNoteTable(
  scope: Construct,
  id: string,
  options: DMSNoteTableOptions = {},
): dynamodb.Table {
  const table = new dynamodb.Table(scope, id, {
    tableName: 'dms_notes',
    partitionKey: { name: 'PK', type: dynamodb.AttributeType.STRING },
    sortKey: { name: 'SK', type: dynamodb.AttributeType.STRING },
    billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
    timeToLiveAttribute: 'ttl',
    ...options,
  });

  table.addGlobalSecondaryIndex({
    indexName: 'gsi-title',
    partitionKey: { name: 'title', type: dynamodb.AttributeType.STRING },
    sortKey: { name: 'createdAt', type: dynamodb.AttributeType.STRING },
    projectionType: dynamodb.ProjectionType.INCLUDE,
    nonKeyAttributes: ['count', 'payload'],
  });

  return table;
}
