package dms

import (
	"bytes"
	"fmt"
	"strings"
)

// generateCDK emits AWS CDK (aws-cdk-lib) DynamoDB Table constructs for every
// model in the document. The emitted table/GSI/LSI/TTL shape is derived from
// the same DMS document that `tabletheory validate` reads, so infrastructure
// definitions cannot drift from the runtime model contract. Output is
// deterministic (models keep document order; index projections are sorted) so
// it can be committed and drift-gated like the other generators.
func generateCDK(models []Model, _ GenerateOptions) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by tabletheory gen --cdk; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "import type { Construct } from 'constructs';\n")
	fmt.Fprintf(&out, "import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';\n\n")
	for i, m := range models {
		if err := generateCDKModel(&out, m); err != nil {
			return nil, err
		}
		if i != len(models)-1 {
			fmt.Fprintf(&out, "\n")
		}
	}
	return out.Bytes(), nil
}

func generateCDKModel(out *bytes.Buffer, m Model) error {
	name := exportName(m.Name)
	if name == "" {
		return fmt.Errorf("DMS model %q cannot be converted to a TypeScript identifier", m.Name)
	}
	partitionType, err := cdkAttributeType(m.Keys.Partition.Type)
	if err != nil {
		return fmt.Errorf("model %s partition key: %w", m.Name, err)
	}

	fmt.Fprintf(out, "export type %sTableOptions = Partial<dynamodb.TableProps>;\n\n", name)
	fmt.Fprintf(out, "export function create%sTable(\n", name)
	fmt.Fprintf(out, "  scope: Construct,\n")
	fmt.Fprintf(out, "  id: string,\n")
	fmt.Fprintf(out, "  options: %sTableOptions = {},\n", name)
	fmt.Fprintf(out, "): dynamodb.Table {\n")
	fmt.Fprintf(out, "  const table = new dynamodb.Table(scope, id, {\n")
	fmt.Fprintf(out, "    tableName: %s,\n", tsString(m.Table.Name))
	fmt.Fprintf(out, "    partitionKey: { name: %s, type: %s },\n", tsString(m.Keys.Partition.Attribute), partitionType)
	if m.Keys.Sort != nil {
		sortType, err := cdkAttributeType(m.Keys.Sort.Type)
		if err != nil {
			return fmt.Errorf("model %s sort key: %w", m.Name, err)
		}
		fmt.Fprintf(out, "    sortKey: { name: %s, type: %s },\n", tsString(m.Keys.Sort.Attribute), sortType)
	}
	fmt.Fprintf(out, "    billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,\n")
	if ttl := cdkTTLAttribute(m); ttl != "" {
		fmt.Fprintf(out, "    timeToLiveAttribute: %s,\n", tsString(ttl))
	}
	fmt.Fprintf(out, "    ...options,\n")
	fmt.Fprintf(out, "  });\n")

	for _, idx := range sortedIndexes(m.Indexes) {
		if err := generateCDKIndex(out, m.Name, idx); err != nil {
			return err
		}
	}

	fmt.Fprintf(out, "\n  return table;\n")
	fmt.Fprintf(out, "}\n")
	return nil
}

func generateCDKIndex(out *bytes.Buffer, modelName string, idx Index) error {
	proj := normalizeProjection(idx.Projection)
	if idx.Type == indexTypeLSI {
		fmt.Fprintf(out, "\n  table.addLocalSecondaryIndex({\n")
		fmt.Fprintf(out, "    indexName: %s,\n", tsString(idx.Name))
		if idx.Sort != nil {
			sortType, err := cdkAttributeType(idx.Sort.Type)
			if err != nil {
				return fmt.Errorf("model %s index %s sort key: %w", modelName, idx.Name, err)
			}
			fmt.Fprintf(out, "    sortKey: { name: %s, type: %s },\n", tsString(idx.Sort.Attribute), sortType)
		}
	} else {
		partitionType, err := cdkAttributeType(idx.Partition.Type)
		if err != nil {
			return fmt.Errorf("model %s index %s partition key: %w", modelName, idx.Name, err)
		}
		fmt.Fprintf(out, "\n  table.addGlobalSecondaryIndex({\n")
		fmt.Fprintf(out, "    indexName: %s,\n", tsString(idx.Name))
		fmt.Fprintf(out, "    partitionKey: { name: %s, type: %s },\n", tsString(idx.Partition.Attribute), partitionType)
		if idx.Sort != nil {
			sortType, err := cdkAttributeType(idx.Sort.Type)
			if err != nil {
				return fmt.Errorf("model %s index %s sort key: %w", modelName, idx.Name, err)
			}
			fmt.Fprintf(out, "    sortKey: { name: %s, type: %s },\n", tsString(idx.Sort.Attribute), sortType)
		}
	}
	fmt.Fprintf(out, "    projectionType: %s,\n", cdkProjectionType(proj.Type))
	if proj.Type == "INCLUDE" && len(proj.Fields) > 0 {
		fmt.Fprintf(out, "    nonKeyAttributes: [%s],\n", tsStringList(proj.Fields))
	}
	fmt.Fprintf(out, "  });\n")
	return nil
}

func cdkAttributeType(dmsType string) (string, error) {
	switch dmsType {
	case "S":
		return "dynamodb.AttributeType.STRING", nil
	case "N":
		return "dynamodb.AttributeType.NUMBER", nil
	case "B":
		return "dynamodb.AttributeType.BINARY", nil
	default:
		return "", fmt.Errorf("unsupported key attribute type %q (want S, N, or B)", dmsType)
	}
}

func cdkProjectionType(projectionType string) string {
	switch projectionType {
	case "KEYS_ONLY":
		return "dynamodb.ProjectionType.KEYS_ONLY"
	case "INCLUDE":
		return "dynamodb.ProjectionType.INCLUDE"
	default:
		return "dynamodb.ProjectionType.ALL"
	}
}

func cdkTTLAttribute(m Model) string {
	for _, attr := range m.Attributes {
		if hasRole(attr.Roles, "ttl") {
			return attr.Attribute
		}
	}
	return ""
}

func tsStringList(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = tsString(v)
	}
	return strings.Join(parts, ", ")
}
