package dms

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"
)

type GenerateOptions struct {
	Lang          string
	PackageName   string
	ModelName     string
	RuntimeImport string
}

const (
	modeMutable         = "mutable"
	projectionAll       = "ALL"
	projectionInclude   = "INCLUDE"
	indexTypeLSI        = "LSI"
	attributeTypeBool   = "BOOL"
	formatDecimalString = "decimal_string"
	attributeTypeNull   = "NULL"
	pyDefaultFactorySet = "default_factory=set"
	pyNone              = "None"
)

func Generate(doc *Document, opts GenerateOptions) ([]byte, error) {
	if doc == nil {
		return nil, fmt.Errorf("DMS document is nil")
	}
	models := doc.Models
	if opts.ModelName != "" {
		model, ok := FindModel(doc, opts.ModelName)
		if !ok {
			return nil, fmt.Errorf("DMS model not found: %s", opts.ModelName)
		}
		models = []Model{*model}
	}
	if len(models) == 0 {
		return nil, fmt.Errorf("DMS document has no models to generate")
	}

	switch opts.Lang {
	case "go":
		return generateGo(models, opts)
	case "ts", "typescript":
		return generateTypeScript(models, opts)
	case "py", "python":
		return generatePython(models, opts)
	case "cdk":
		return generateCDK(models, opts)
	default:
		return nil, fmt.Errorf("unsupported generation language %q (want go, ts, py, or cdk)", opts.Lang)
	}
}

func generateGo(models []Model, opts GenerateOptions) ([]byte, error) {
	pkg := opts.PackageName
	if pkg == "" {
		pkg = "models"
	}
	if !isGoIdentifier(pkg) || !unicode.IsLower([]rune(pkg)[0]) {
		return nil, fmt.Errorf("invalid Go package name %q", pkg)
	}

	imports := map[string]struct{}{}
	var body bytes.Buffer
	for _, model := range models {
		if err := generateGoModel(&body, model, imports); err != nil {
			return nil, err
		}
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by tabletheory gen --lang go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", pkg)
	if len(imports) > 0 {
		std, thirdParty := partitionGoImports(sortedKeys(imports))
		fmt.Fprintf(&out, "import (\n")
		for _, imp := range std {
			fmt.Fprintf(&out, "\t%q\n", imp)
		}
		if len(std) > 0 && len(thirdParty) > 0 {
			fmt.Fprintf(&out, "\n")
		}
		for _, imp := range thirdParty {
			fmt.Fprintf(&out, "\t%q\n", imp)
		}
		fmt.Fprintf(&out, ")\n\n")
	}
	if goNeedsDecimalString(models) {
		fmt.Fprintf(&out, "type DecimalString string\n\n")
	}
	out.Write(body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	return formatted, nil
}

func generateGoModel(out *bytes.Buffer, m Model, imports map[string]struct{}) error {
	modelName := exportName(m.Name)
	if modelName == "" {
		return fmt.Errorf("DMS model %q cannot be converted to a Go identifier", m.Name)
	}

	fieldNames := map[string]int{}
	fmt.Fprintf(out, "type %s struct {\n", modelName)
	if m.Naming.Convention == namingConventionSnakeCase || m.Naming.Convention == namingConventionDynamORM {
		fmt.Fprintf(out, "\t_ struct{} `theorydb:\"naming:%s\" json:\"-\"`\n", m.Naming.Convention)
	}
	for _, attr := range m.Attributes {
		fieldName := uniqueGoFieldName(exportName(attr.Attribute), fieldNames)
		fieldType, err := goTypeForAttribute(attr, imports)
		if err != nil {
			return fmt.Errorf("model %s attribute %s: %w", m.Name, attr.Attribute, err)
		}
		tag := goTheorydbTag(attr, m.Indexes)
		jsonTag := attr.Attribute
		if attr.OmitEmpty {
			jsonTag += ",omitempty"
		}
		fmt.Fprintf(out, "\t%s %s `theorydb:\"%s\" json:\"%s\"`\n", fieldName, fieldType, tag, jsonTag)
	}
	fmt.Fprintf(out, "}\n\n")
	fmt.Fprintf(out, "func (%s) TableName() string { return %q }\n\n", modelName, m.Table.Name)

	policy := normalizeWritePolicy(m.WritePolicy)
	if policy.Mode != modeMutable || len(policy.ProtectedAttributes) > 0 {
		imports["github.com/theory-cloud/tabletheory/pkg/model"] = struct{}{}
		fmt.Fprintf(out, "func (%s) WritePolicy() model.WritePolicy {\n", modelName)
		fmt.Fprintf(out, "\treturn model.WritePolicy{\n")
		fmt.Fprintf(out, "\t\tMode: model.WritePolicyMode(%q),\n", policy.Mode)
		fmt.Fprintf(out, "\t\tProtectedAttributes: []string{%s},\n", quotedStringList(policy.ProtectedAttributes))
		fmt.Fprintf(out, "\t}\n}\n\n")
	}
	if hasNonDefaultProjection(m.Indexes) {
		fmt.Fprintf(out, "func (%s) TableTheoryIndexProjections() map[string]struct {\n", modelName)
		fmt.Fprintf(out, "\tType string\n\tFields []string\n} {\n")
		fmt.Fprintf(out, "\treturn map[string]struct {\n\t\tType string\n\t\tFields []string\n\t}{\n")
		for _, idx := range sortedIndexes(m.Indexes) {
			proj := normalizeProjection(idx.Projection)
			if proj.Type == projectionAll && len(proj.Fields) == 0 {
				continue
			}
			fmt.Fprintf(out, "\t\t%q: {Type: %q, Fields: []string{%s}},\n", idx.Name, proj.Type, quotedStringList(proj.Fields))
		}
		fmt.Fprintf(out, "\t}\n}\n\n")
	}
	return nil
}

func goTheorydbTag(attr Attribute, indexes []Index) string {
	parts := make([]string, 0, 6)
	for _, role := range attr.Roles {
		switch role {
		case "pk", "sk", "created_at", "updated_at", "version", "ttl":
			parts = append(parts, role)
		}
	}
	parts = append(parts, "attr:"+attr.Attribute)
	if attr.OmitEmpty {
		parts = append(parts, "omitempty")
	}
	if attr.Encryption != nil {
		parts = append(parts, "encrypted")
	}
	if attr.JSON {
		parts = append(parts, "json")
	}
	if attr.Binary {
		parts = append(parts, "binary")
	}
	if isSetType(attr.Type) {
		parts = append(parts, "set")
	}
	for _, idx := range sortedIndexes(indexes) {
		if idx.Partition.Attribute == attr.Attribute {
			if idx.Type == indexTypeLSI {
				parts = append(parts, "lsi:"+idx.Name+",pk")
			} else {
				parts = append(parts, "index:"+idx.Name+",pk")
			}
		}
		if idx.Sort != nil && idx.Sort.Attribute == attr.Attribute {
			if idx.Type == indexTypeLSI {
				parts = append(parts, "lsi:"+idx.Name+",sk")
			} else {
				parts = append(parts, "index:"+idx.Name+",sk")
			}
		}
	}
	return strings.Join(parts, ",")
}

func goTypeForAttribute(attr Attribute, imports map[string]struct{}) (string, error) {
	if hasRole(attr.Roles, "created_at") || hasRole(attr.Roles, "updated_at") {
		imports["time"] = struct{}{}
		return "time.Time", nil
	}
	switch attr.Type {
	case "S":
		return "string", nil
	case "N":
		if attr.Format == formatDecimalString {
			return "DecimalString", nil
		}
		return "int64", nil
	case "B":
		return "[]byte", nil
	case attributeTypeBool:
		return "bool", nil
	case "M":
		return "map[string]any", nil
	case "L":
		return "[]any", nil
	case "SS":
		return "[]string", nil
	case "NS":
		return "[]int64", nil
	case "BS":
		return "[][]byte", nil
	case attributeTypeNull:
		return "any", nil
	default:
		return "", fmt.Errorf("unsupported DMS attribute type %q", attr.Type)
	}
}

func generateTypeScript(models []Model, opts GenerateOptions) ([]byte, error) {
	runtimeImport := opts.RuntimeImport
	if runtimeImport == "" {
		runtimeImport = "@theory-cloud/tabletheory-ts"
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by tabletheory gen --lang ts; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "import { defineModel } from %s;\n\n", tsString(runtimeImport))
	for i, model := range models {
		name := exportName(model.Name)
		if name == "" {
			return nil, fmt.Errorf("DMS model %q cannot be converted to a TypeScript identifier", model.Name)
		}
		fmt.Fprintf(&out, "export const %sSchema = %s as const;\n\n", name, tsObject(modelToSchemaMap(model), 0))
		fmt.Fprintf(&out, "export const %sModel = defineModel(%sSchema);\n", name, name)
		if i != len(models)-1 {
			fmt.Fprintf(&out, "\n")
		}
	}
	return out.Bytes(), nil
}

func modelToSchemaMap(m Model) map[string]any {
	out := map[string]any{
		"name":       m.Name,
		"table":      map[string]any{"name": m.Table.Name},
		"keys":       keysToMap(m.Keys),
		"attributes": attributesToMaps(m.Attributes),
	}
	if m.Naming.Convention != "" {
		out["naming"] = map[string]any{"convention": m.Naming.Convention}
	}
	policy := normalizeWritePolicy(m.WritePolicy)
	if policy.Mode != modeMutable || len(policy.ProtectedAttributes) > 0 {
		out["write_policy"] = map[string]any{
			"mode":                 policy.Mode,
			"protected_attributes": policy.ProtectedAttributes,
		}
	}
	if len(m.Indexes) > 0 {
		out["indexes"] = indexesToMaps(m.Indexes)
	}
	return out
}

func keysToMap(keys Keys) map[string]any {
	out := map[string]any{"partition": keyToMap(keys.Partition)}
	if keys.Sort != nil {
		out["sort"] = keyToMap(*keys.Sort)
	}
	return out
}

func keyToMap(key KeyAttribute) map[string]any {
	return map[string]any{"attribute": key.Attribute, "type": key.Type}
}

func attributesToMaps(attrs []Attribute) []any {
	ordered := append([]Attribute(nil), attrs...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Attribute < ordered[j].Attribute })
	out := make([]any, 0, len(ordered))
	for _, attr := range ordered {
		m := map[string]any{"attribute": attr.Attribute, "type": attr.Type}
		if attr.Format != "" {
			m["format"] = attr.Format
		}
		if len(attr.Roles) > 0 {
			roles := append([]string(nil), attr.Roles...)
			sort.Strings(roles)
			m["roles"] = roles
		}
		if attr.Required {
			m["required"] = true
		}
		if attr.Optional {
			m["optional"] = true
		}
		if attr.OmitEmpty {
			m["omit_empty"] = true
		}
		if attr.JSON {
			m["json"] = true
		}
		if attr.Binary {
			m["binary"] = true
		}
		if attr.Encryption != nil {
			m["encryption"] = map[string]any{"v": 1}
		}
		out = append(out, m)
	}
	return out
}

func indexesToMaps(indexes []Index) []any {
	out := make([]any, 0, len(indexes))
	for _, idx := range sortedIndexes(indexes) {
		m := map[string]any{
			"name":       idx.Name,
			"type":       idx.Type,
			"partition":  keyToMap(idx.Partition),
			"projection": projectionToMap(normalizeProjection(idx.Projection)),
		}
		if idx.Sort != nil {
			m["sort"] = keyToMap(*idx.Sort)
		}
		out = append(out, m)
	}
	return out
}

func projectionToMap(proj Projection) map[string]any {
	out := map[string]any{"type": proj.Type}
	if len(proj.Fields) > 0 {
		fields := append([]string(nil), proj.Fields...)
		sort.Strings(fields)
		out["fields"] = fields
	}
	return out
}

func generatePython(models []Model, _ GenerateOptions) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "# Code generated by tabletheory gen --lang py; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "from __future__ import annotations\n\n")
	imports := map[string]struct{}{"dataclasses": {}, "theorydb_py": {}}
	if pythonNeedsAny(models) {
		imports["typing"] = struct{}{}
	}
	fmt.Fprintf(&out, "from dataclasses import dataclass\n")
	if pythonNeedsDecimal(models) {
		fmt.Fprintf(&out, "from decimal import Decimal\n")
	}
	if _, ok := imports["typing"]; ok {
		fmt.Fprintf(&out, "from typing import Any\n")
	}
	theoryImports := []string{"ModelDefinition", "theorydb_field"}
	if pythonNeedsProjection(models) {
		theoryImports = append(theoryImports, "Projection")
	}
	if pythonNeedsWritePolicy(models) {
		theoryImports = append(theoryImports, "WritePolicy")
	}
	if pythonNeedsGSI(models) {
		theoryImports = append(theoryImports, "gsi")
	}
	if pythonNeedsLSI(models) {
		theoryImports = append(theoryImports, "lsi")
	}
	sort.Strings(theoryImports)
	fmt.Fprintf(&out, "\nfrom theorydb_py import %s\n\n\n", strings.Join(theoryImports, ", "))
	for _, model := range models {
		if err := generatePythonModel(&out, model); err != nil {
			return nil, err
		}
	}
	return []byte(strings.TrimRight(out.String(), "\n") + "\n"), nil
}

func generatePythonModel(out *bytes.Buffer, m Model) error {
	className := exportName(m.Name)
	if className == "" {
		return fmt.Errorf("DMS model %q cannot be converted to a Python class name", m.Name)
	}
	fmt.Fprintf(out, "@dataclass(frozen=True)\n")
	fmt.Fprintf(out, "class %s:\n", className)
	if len(m.Attributes) == 0 {
		fmt.Fprintf(out, "    pass\n\n")
		return nil
	}
	fieldNames := map[string]int{}
	pythonFieldByAttribute := make(map[string]string, len(m.Attributes))
	fields := make([]pythonGeneratedField, 0, len(m.Attributes))
	for _, attr := range m.Attributes {
		name := uniquePyFieldName(snakeIdentifier(attr.Attribute), fieldNames)
		pythonFieldByAttribute[attr.Attribute] = name
		typeExpr, defaultExpr, err := pyTypeAndDefault(attr)
		if err != nil {
			return fmt.Errorf("model %s attribute %s: %w", m.Name, attr.Attribute, err)
		}
		args := pyTheorydbFieldArgs(attr)
		if defaultExpr != "" {
			if strings.HasPrefix(defaultExpr, "default_factory=") {
				args = append(args, defaultExpr)
			} else {
				args = append(args, "default="+defaultExpr)
			}
		}
		fields = append(fields, pythonGeneratedField{
			Name:        name,
			TypeExpr:    typeExpr,
			DefaultExpr: defaultExpr,
			Args:        args,
		})
	}
	for _, field := range orderPythonDataclassFields(fields) {
		fmt.Fprintf(out, "    %s: %s = theorydb_field(%s)\n", field.Name, field.TypeExpr, strings.Join(field.Args, ", "))
	}
	fmt.Fprintf(out, "\n\n")
	fmt.Fprintf(out, "%sDefinition = ModelDefinition.from_dataclass(\n", className)
	fmt.Fprintf(out, "    %s,\n", className)
	fmt.Fprintf(out, "    table_name=%s", pyString(m.Table.Name))
	policy := normalizeWritePolicy(m.WritePolicy)
	if policy.Mode != modeMutable || len(policy.ProtectedAttributes) > 0 {
		fmt.Fprintf(out, ",\n    write_policy=WritePolicy(mode=%s, protected_attributes=%s)", pyString(policy.Mode), pyTupleLiteral(policy.ProtectedAttributes))
	}
	if len(m.Indexes) > 0 {
		fmt.Fprintf(out, ",\n    indexes=[\n")
		for _, idx := range sortedIndexes(m.Indexes) {
			fmt.Fprintf(out, "        %s,\n", pyIndexSpec(idx, pythonFieldByAttribute))
		}
		fmt.Fprintf(out, "    ]")
	}
	fmt.Fprintf(out, ",\n)\n\n")
	return nil
}

type pythonGeneratedField struct {
	Name        string
	TypeExpr    string
	DefaultExpr string
	Args        []string
}

func orderPythonDataclassFields(fields []pythonGeneratedField) []pythonGeneratedField {
	ordered := append([]pythonGeneratedField(nil), fields...)
	sort.SliceStable(ordered, func(i, j int) bool {
		iRequired := ordered[i].DefaultExpr == ""
		jRequired := ordered[j].DefaultExpr == ""
		return iRequired && !jRequired
	})
	return ordered
}

func pyTheorydbFieldArgs(attr Attribute) []string {
	args := []string{"name=" + pyString(attr.Attribute)}
	roles := append([]string(nil), attr.Roles...)
	sort.Strings(roles)
	if len(roles) > 0 {
		args = append(args, "roles=["+pyListStrings(roles)+"]")
	}
	if attr.OmitEmpty {
		args = append(args, "omitempty=True")
	}
	if isSetType(attr.Type) {
		args = append(args, "set_=True")
	}
	if attr.JSON {
		args = append(args, "json=True")
	}
	if attr.Binary {
		args = append(args, "binary=True")
	}
	if attr.Encryption != nil {
		args = append(args, "encrypted=True")
	}
	return args
}

type pyTypeDefault struct {
	Type    string
	Default string
}

var pyTypeDefaults = map[string]pyTypeDefault{
	"S":               {Type: "str", Default: pyString("")},
	"N":               {Type: "int", Default: "0"},
	"B":               {Type: "bytes", Default: "b\"\""},
	attributeTypeBool: {Type: "bool", Default: "False"},
	"M":               {Type: "dict[str, Any]", Default: "default_factory=dict"},
	"L":               {Type: "list[Any]", Default: "default_factory=list"},
	"SS":              {Type: "set[str]", Default: pyDefaultFactorySet},
	"NS":              {Type: "set[int]", Default: pyDefaultFactorySet},
	"BS":              {Type: "set[bytes]", Default: pyDefaultFactorySet},
	attributeTypeNull: {Type: pyNone, Default: pyNone},
}

func pyTypeAndDefault(attr Attribute) (string, string, error) {
	if attr.Type == "N" && attr.Format == formatDecimalString {
		return "Decimal", pyDefaultExpression(attr, `Decimal("0")`), nil
	}
	spec, ok := pyTypeDefaults[attr.Type]
	if !ok {
		return "", "", fmt.Errorf("unsupported DMS attribute type %q", attr.Type)
	}
	return spec.Type, pyDefaultExpression(attr, spec.Default), nil
}

func pyDefaultExpression(attr Attribute, fallback string) string {
	if hasRole(attr.Roles, "pk") || hasRole(attr.Roles, "sk") {
		return ""
	}
	if attr.Required && !attr.Optional && !attr.OmitEmpty {
		return ""
	}
	return fallback
}

func pyIndexSpec(idx Index, pythonFieldByAttribute map[string]string) string {
	proj := normalizeProjection(idx.Projection)
	projExpr := "Projection.all()"
	switch proj.Type {
	case "KEYS_ONLY":
		projExpr = "Projection.keys_only()"
	case projectionInclude:
		projExpr = "Projection.include(" + pyListAsArgs(proj.Fields) + ")"
	}
	if idx.Type == indexTypeLSI {
		sortField := ""
		if idx.Sort != nil {
			sortField = pythonFieldByAttribute[idx.Sort.Attribute]
		}
		return strings.Join([]string{
			"lsi(",
			"    " + pyString(idx.Name) + ",",
			"    sort=" + pyString(sortField) + ",",
			"    projection=" + projExpr + ",",
			")",
		}, "\n        ")
	}
	partitionField := pythonFieldByAttribute[idx.Partition.Attribute]
	if idx.Sort != nil {
		sortField := pythonFieldByAttribute[idx.Sort.Attribute]
		return strings.Join([]string{
			"gsi(",
			"    " + pyString(idx.Name) + ",",
			"    partition=" + pyString(partitionField) + ",",
			"    sort=" + pyString(sortField) + ",",
			"    projection=" + projExpr + ",",
			")",
		}, "\n        ")
	}
	return strings.Join([]string{
		"gsi(",
		"    " + pyString(idx.Name) + ",",
		"    partition=" + pyString(partitionField) + ",",
		"    projection=" + projExpr + ",",
		")",
	}, "\n        ")
}

func tsObject(value any, indent int) string {
	switch v := value.(type) {
	case map[string]any:
		keys := make([]string, 0, len(v))
		for key := range v {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		// Keep common schema keys in a readable order.
		keys = stableSchemaKeyOrder(keys)
		var b strings.Builder
		b.WriteString("{\n")
		for _, key := range keys {
			b.WriteString(strings.Repeat(" ", indent+2))
			b.WriteString(key)
			b.WriteString(": ")
			b.WriteString(tsObject(v[key], indent+2))
			b.WriteString(",\n")
		}
		b.WriteString(strings.Repeat(" ", indent))
		b.WriteString("}")
		return b.String()
	case []any:
		if len(v) == 0 {
			return "[]"
		}
		var b strings.Builder
		b.WriteString("[\n")
		for _, item := range v {
			b.WriteString(strings.Repeat(" ", indent+2))
			b.WriteString(tsObject(item, indent+2))
			b.WriteString(",\n")
		}
		b.WriteString(strings.Repeat(" ", indent))
		b.WriteString("]")
		return b.String()
	case []string:
		if len(v) == 0 {
			return "[]"
		}
		parts := make([]string, len(v))
		for i, item := range v {
			parts[i] = tsString(item)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case string:
		return tsString(v)
	case bool:
		if v {
			return "true"
		}
		return "false"
	case nil:
		return "null"
	default:
		encoded, err := json.Marshal(v)
		if err != nil {
			return "null"
		}
		return string(encoded)
	}
}

func stableSchemaKeyOrder(keys []string) []string {
	order := []string{"name", "table", "naming", "keys", "write_policy", "attributes", "indexes", "attribute", "type", "format", "required", "optional", "omit_empty", "roles", "json", "binary", "encryption", "partition", "sort", "projection", "fields", "mode", "protected_attributes"}
	rank := make(map[string]int, len(order))
	for i, key := range order {
		rank[key] = i
	}
	sort.SliceStable(keys, func(i, j int) bool {
		ri, iok := rank[keys[i]]
		rj, jok := rank[keys[j]]
		if iok && jok {
			return ri < rj
		}
		if iok != jok {
			return iok
		}
		return keys[i] < keys[j]
	})
	return keys
}

func sortedIndexes(indexes []Index) []Index {
	out := append([]Index(nil), indexes...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func sortedKeys(m map[string]struct{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func partitionGoImports(imports []string) ([]string, []string) {
	var std []string
	var thirdParty []string
	for _, imp := range imports {
		first := imp
		if idx := strings.IndexByte(first, '/'); idx >= 0 {
			first = first[:idx]
		}
		if strings.Contains(first, ".") {
			thirdParty = append(thirdParty, imp)
		} else {
			std = append(std, imp)
		}
	}
	return std, thirdParty
}

func normalizeProjection(proj Projection) Projection {
	out := proj
	if out.Type == "" {
		out.Type = projectionAll
	}
	out.Fields = append([]string(nil), out.Fields...)
	sort.Strings(out.Fields)
	if out.Fields == nil {
		out.Fields = []string{}
	}
	return out
}

func hasNonDefaultProjection(indexes []Index) bool {
	for _, idx := range indexes {
		proj := normalizeProjection(idx.Projection)
		if proj.Type != projectionAll || len(proj.Fields) > 0 {
			return true
		}
	}
	return false
}

func hasRole(roles []string, want string) bool {
	for _, role := range roles {
		if role == want {
			return true
		}
	}
	return false
}

func isSetType(attrType string) bool {
	return attrType == "SS" || attrType == "NS" || attrType == "BS"
}

func exportName(raw string) string {
	parts := identifierParts(raw)
	if len(parts) == 0 {
		return ""
	}
	var b strings.Builder
	for _, part := range parts {
		upper := strings.ToUpper(part)
		if isCommonInitialism(upper) {
			b.WriteString(upper)
			continue
		}
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		b.WriteRune(unicode.ToUpper(runes[0]))
		for _, r := range runes[1:] {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" || !isGoIdentifier(out) || !unicode.IsLetter([]rune(out)[0]) {
		return ""
	}
	return out
}

func snakeIdentifier(raw string) string {
	parts := identifierParts(raw)
	if len(parts) == 0 {
		return "field"
	}
	for i := range parts {
		parts[i] = strings.ToLower(parts[i])
	}
	out := strings.Join(parts, "_")
	if out == "" || !isPyIdentifier(out) || isPyKeyword(out) {
		out = "field_" + out
	}
	return out
}

func identifierParts(raw string) []string {
	var parts []string
	var current []rune
	flush := func() {
		if len(current) > 0 {
			parts = append(parts, string(current))
			current = nil
		}
	}
	var prev rune
	for i, r := range raw {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if i > 0 && unicode.IsUpper(r) && prev != 0 && (unicode.IsLower(prev) || unicode.IsDigit(prev)) {
				flush()
			}
			current = append(current, r)
			prev = r
			continue
		}
		flush()
		prev = 0
	}
	flush()
	return parts
}

func uniqueGoFieldName(base string, seen map[string]int) string {
	if base == "" {
		base = "Field"
	}
	if !isGoIdentifier(base) || !unicode.IsLetter([]rune(base)[0]) {
		base = "Field" + base
	}
	count := seen[base]
	seen[base] = count + 1
	if count == 0 {
		return base
	}
	return fmt.Sprintf("%s%d", base, count+1)
}

func uniquePyFieldName(base string, seen map[string]int) string {
	if base == "" {
		base = "field"
	}
	count := seen[base]
	seen[base] = count + 1
	if count == 0 {
		return base
	}
	return fmt.Sprintf("%s_%d", base, count+1)
}

func isGoIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if i == 0 {
			if !unicode.IsLetter(r) && r != '_' {
				return false
			}
			continue
		}
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return false
		}
	}
	return true
}

func isPyIdentifier(s string) bool { return isGoIdentifier(s) }

func isPyKeyword(s string) bool {
	switch s {
	case "False", pyNone, "True", "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield":
		return true
	default:
		return false
	}
}

func isCommonInitialism(s string) bool {
	switch s {
	case "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "KMS", "PK", "QPS", "SK", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TTL", "UID", "URI", "URL", "UTF8", "UUID", "VM", "XML", "XMPP", "XSRF", "XSS":
		return true
	default:
		return false
	}
}

func quotedStringList(values []string) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = fmt.Sprintf("%q", value)
	}
	return strings.Join(parts, ", ")
}

func pyString(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(encoded)
}

func pyListStrings(values []string) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = pyString(value)
	}
	return strings.Join(parts, ", ")
}

func pyTupleLiteral(values []string) string {
	if len(values) == 0 {
		return "()"
	}
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = pyString(value)
	}
	if len(parts) == 1 {
		return "(" + parts[0] + ",)"
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func pyListAsArgs(values []string) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = pyString(value)
	}
	return strings.Join(parts, ", ")
}

func tsString(value string) string {
	var b strings.Builder
	b.WriteByte('\'')
	for _, r := range value {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '\'':
			b.WriteString(`\'`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

func goNeedsDecimalString(models []Model) bool {
	for _, m := range models {
		for _, attr := range m.Attributes {
			if attr.Type == "N" && attr.Format == formatDecimalString {
				return true
			}
		}
	}
	return false
}

func pythonNeedsDecimal(models []Model) bool {
	for _, m := range models {
		for _, attr := range m.Attributes {
			if attr.Type == "N" && attr.Format == formatDecimalString {
				return true
			}
		}
	}
	return false
}

func pythonNeedsAny(models []Model) bool {
	for _, m := range models {
		for _, attr := range m.Attributes {
			if attr.Type == "M" || attr.Type == "L" {
				return true
			}
		}
	}
	return false
}

func pythonNeedsProjection(models []Model) bool {
	for _, m := range models {
		if len(m.Indexes) > 0 {
			return true
		}
	}
	return false
}

func pythonNeedsWritePolicy(models []Model) bool {
	for _, m := range models {
		policy := normalizeWritePolicy(m.WritePolicy)
		if policy.Mode != modeMutable || len(policy.ProtectedAttributes) > 0 {
			return true
		}
	}
	return false
}

func pythonNeedsGSI(models []Model) bool {
	for _, m := range models {
		for _, idx := range m.Indexes {
			if idx.Type == "GSI" {
				return true
			}
		}
	}
	return false
}

func pythonNeedsLSI(models []Model) bool {
	for _, m := range models {
		for _, idx := range m.Indexes {
			if idx.Type == indexTypeLSI {
				return true
			}
		}
	}
	return false
}
