// Code generated by tabletheory gen --lang go; DO NOT EDIT.

package codegenfixture

import (
	"time"

	"github.com/theory-cloud/tabletheory/v2/pkg/model"
)

type DMSNote struct {
	PK        string         `theorydb:"pk,attr:PK" json:"PK"`
	SK        string         `theorydb:"sk,attr:SK" json:"SK"`
	Title     string         `theorydb:"attr:title,omitempty,index:gsi-title,pk" json:"title,omitempty"`
	Count     int64          `theorydb:"attr:count" json:"count"`
	Tags      []string       `theorydb:"attr:tags,omitempty,set" json:"tags,omitempty"`
	Payload   map[string]any `theorydb:"attr:payload,json" json:"payload"`
	Blob      []byte         `theorydb:"attr:blob,binary" json:"blob"`
	Secret    string         `theorydb:"attr:secret,omitempty,encrypted" json:"secret,omitempty"`
	CreatedAt time.Time      `theorydb:"created_at,attr:createdAt,index:gsi-title,sk" json:"createdAt"`
	Version   int64          `theorydb:"version,attr:version" json:"version"`
	TTL       int64          `theorydb:"ttl,attr:ttl,omitempty" json:"ttl,omitempty"`
}

func (DMSNote) TableName() string { return "dms_notes" }

func (DMSNote) WritePolicy() model.WritePolicy {
	return model.WritePolicy{
		Mode:                model.WritePolicyMode("mutable"),
		ProtectedAttributes: []string{"title"},
	}
}

func (DMSNote) TableTheoryIndexProjections() map[string]struct {
	Type   string
	Fields []string
} {
	return map[string]struct {
		Type   string
		Fields []string
	}{
		"gsi-title": {Type: "INCLUDE", Fields: []string{"count", "payload"}},
	}
}
