// Code generated by tabletheory gen --cdk; DO NOT EDIT.
import type { Construct } from 'constructs';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';

export type DemoItemTableOptions = Partial<dynamodb.TableProps>;

export function createDemoItemTable(
  scope: Construct,
  id: string,
  options: DemoItemTableOptions = {},
): dynamodb.Table {
  const table = new dynamodb.Table(scope, id, {
    tableName: 'demo_multilang',
    partitionKey: { name: 'PK', type: dynamodb.AttributeType.STRING },
    sortKey: { name: 'SK', type: dynamodb.AttributeType.STRING },
    billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
    ...options,
  });

  return table;
}
