// Code generated by tabletheory gen --lang go; DO NOT EDIT.

package driver

type DecimalString string

type NumberPrecision struct {
	PK             string        `theorydb:"pk,attr:PK" json:"PK"`
	SK             string        `theorydb:"sk,attr:SK" json:"SK"`
	LargeInteger   DecimalString `theorydb:"attr:largeInteger" json:"largeInteger"`
	PreciseDecimal DecimalString `theorydb:"attr:preciseDecimal" json:"preciseDecimal"`
}

func (NumberPrecision) TableName() string { return "number_precision_contract" }
