// Code generated by tabletheory gen --lang go; DO NOT EDIT.

package driver

type SnakeCaseRecord struct {
	_           struct{} `theorydb:"naming:snake_case" json:"-"`
	PK          string   `theorydb:"pk,attr:pk" json:"pk"`
	SK          string   `theorydb:"sk,attr:sk" json:"sk"`
	DisplayName string   `theorydb:"attr:display_name" json:"display_name"`
	EmailHash   string   `theorydb:"attr:email_hash" json:"email_hash"`
}

func (SnakeCaseRecord) TableName() string { return "snake_case_contract" }
