// Code generated by tabletheory gen --lang go; DO NOT EDIT.

package driver

import (
	"time"
)

type Order struct {
	PK        string    `theorydb:"pk,attr:PK" json:"PK"`
	SK        string    `theorydb:"sk,attr:SK" json:"SK"`
	Status    string    `theorydb:"attr:status,omitempty,index:gsi-status,pk" json:"status,omitempty"`
	Amount    int64     `theorydb:"attr:amount,omitempty" json:"amount,omitempty"`
	CreatedAt time.Time `theorydb:"created_at,attr:createdAt,index:gsi-status,sk" json:"createdAt"`
	UpdatedAt time.Time `theorydb:"updated_at,attr:updatedAt" json:"updatedAt"`
	Version   int64     `theorydb:"version,attr:version" json:"version"`
	TTL       int64     `theorydb:"ttl,attr:ttl,omitempty" json:"ttl,omitempty"`
}

func (Order) TableName() string { return "orders_contract" }

func (Order) TableTheoryIndexProjections() map[string]struct {
	Type   string
	Fields []string
} {
	return map[string]struct {
		Type   string
		Fields []string
	}{
		"gsi-status": {Type: "INCLUDE", Fields: []string{"amount"}},
	}
}
