// Code generated by tabletheory gen --lang go; DO NOT EDIT.

package driver

type TypeMatrix struct {
	PK             string         `theorydb:"pk,attr:PK" json:"PK"`
	SK             string         `theorydb:"sk,attr:SK" json:"SK"`
	NumberSet      []int64        `theorydb:"attr:numberSet,set" json:"numberSet"`
	BinaryBlob     []byte         `theorydb:"attr:binaryBlob" json:"binaryBlob"`
	BinarySet      [][]byte       `theorydb:"attr:binarySet,set" json:"binarySet"`
	Flag           bool           `theorydb:"attr:flag" json:"flag"`
	Nothing        any            `theorydb:"attr:nothing" json:"nothing"`
	Items          []any          `theorydb:"attr:items" json:"items"`
	Metadata       map[string]any `theorydb:"attr:metadata" json:"metadata"`
	EmptyNumberSet []int64        `theorydb:"attr:emptyNumberSet,set" json:"emptyNumberSet"`
	EmptyBinarySet [][]byte       `theorydb:"attr:emptyBinarySet,set" json:"emptyBinarySet"`
	OptionalString string         `theorydb:"attr:optionalString" json:"optionalString"`
}

func (TypeMatrix) TableName() string { return "type_matrix_contract" }
