// Code generated by tabletheory gen --lang go; DO NOT EDIT.

package driver

type EncryptedRecord struct {
	PK     string `theorydb:"pk,attr:PK" json:"PK"`
	SK     string `theorydb:"sk,attr:SK" json:"SK"`
	Secret string `theorydb:"attr:secret,encrypted" json:"secret"`
}

func (EncryptedRecord) TableName() string { return "encrypted_records_contract" }
