// Code generated by tabletheory gen --lang go; DO NOT EDIT.

package driver

import (
	"time"

	"github.com/theory-cloud/tabletheory/v3/pkg/model"
)

type ReleaseStateActual struct {
	PK                string         `theorydb:"pk,attr:PK" json:"PK"`
	SK                string         `theorydb:"sk,attr:SK" json:"SK"`
	Status            string         `theorydb:"attr:status,omitempty" json:"status,omitempty"`
	PinnedReleaseID   string         `theorydb:"attr:pinnedReleaseId,omitempty" json:"pinnedReleaseId,omitempty"`
	PreviousReleaseID string         `theorydb:"attr:previousReleaseId,omitempty" json:"previousReleaseId,omitempty"`
	Provenance        map[string]any `theorydb:"attr:provenance,omitempty,json" json:"provenance,omitempty"`
	Confidence        map[string]any `theorydb:"attr:confidence,omitempty,json" json:"confidence,omitempty"`
	UpdatedAt         time.Time      `theorydb:"updated_at,attr:updatedAt" json:"updatedAt"`
	Version           int64          `theorydb:"version,attr:version" json:"version"`
}

func (ReleaseStateActual) TableName() string { return "release_state_contract" }

func (ReleaseStateActual) WritePolicy() model.WritePolicy {
	return model.WritePolicy{
		Mode:                model.WritePolicyMode("mutable"),
		ProtectedAttributes: []string{"pinnedReleaseId"},
	}
}

type ReleaseStateEvent struct {
	PK         string         `theorydb:"pk,attr:PK" json:"PK"`
	SK         string         `theorydb:"sk,attr:SK" json:"SK"`
	ReleaseID  string         `theorydb:"attr:releaseId,omitempty" json:"releaseId,omitempty"`
	EventType  string         `theorydb:"attr:eventType,omitempty" json:"eventType,omitempty"`
	Provenance map[string]any `theorydb:"attr:provenance,omitempty,json" json:"provenance,omitempty"`
	Confidence map[string]any `theorydb:"attr:confidence,omitempty,json" json:"confidence,omitempty"`
	RecordedAt string         `theorydb:"attr:recordedAt,omitempty" json:"recordedAt,omitempty"`
	TTL        int64          `theorydb:"ttl,attr:ttl,omitempty" json:"ttl,omitempty"`
}

func (ReleaseStateEvent) TableName() string { return "release_state_contract" }

func (ReleaseStateEvent) WritePolicy() model.WritePolicy {
	return model.WritePolicy{
		Mode:                model.WritePolicyMode("write_once"),
		ProtectedAttributes: []string{},
	}
}
