# Code generated by tabletheory gen --lang py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass

from theorydb_py import ModelDefinition, theorydb_field


@dataclass(frozen=True)
class EncryptedRecord:
    pk: str = theorydb_field(name="PK", roles=["pk"])
    sk: str = theorydb_field(name="SK", roles=["sk"])
    secret: str = theorydb_field(name="secret", encrypted=True, default="")


EncryptedRecordDefinition = ModelDefinition.from_dataclass(
    EncryptedRecord,
    table_name="encrypted_records_contract",
)
