# Code generated by tabletheory gen --lang py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from theorydb_py import ModelDefinition, theorydb_field


@dataclass(frozen=True)
class NumberPrecision:
    pk: str = theorydb_field(name="PK", roles=["pk"])
    sk: str = theorydb_field(name="SK", roles=["sk"])
    large_integer: Decimal = theorydb_field(name="largeInteger", default=Decimal("0"))
    precise_decimal: Decimal = theorydb_field(name="preciseDecimal", default=Decimal("0"))


NumberPrecisionDefinition = ModelDefinition.from_dataclass(
    NumberPrecision,
    table_name="number_precision_contract",
)
