# Code generated by tabletheory gen --lang py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass

from theorydb_py import ModelDefinition, Projection, gsi, theorydb_field


@dataclass(frozen=True)
class Order:
    pk: str = theorydb_field(name="PK", roles=["pk"])
    sk: str = theorydb_field(name="SK", roles=["sk"])
    status: str = theorydb_field(name="status", omitempty=True, default="")
    amount: int = theorydb_field(name="amount", omitempty=True, default=0)
    created_at: str = theorydb_field(name="createdAt", roles=["created_at"], default="")
    updated_at: str = theorydb_field(name="updatedAt", roles=["updated_at"], default="")
    version: int = theorydb_field(name="version", roles=["version"], default=0)
    ttl: int = theorydb_field(name="ttl", roles=["ttl"], omitempty=True, default=0)


OrderDefinition = ModelDefinition.from_dataclass(
    Order,
    table_name="orders_contract",
    indexes=[
        gsi(
            "gsi-status",
            partition="status",
            sort="created_at",
            projection=Projection.include("amount"),
        ),
    ],
)
