# Code generated by tabletheory gen --lang py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from theorydb_py import ModelDefinition, WritePolicy, theorydb_field


@dataclass(frozen=True)
class ReleaseStateActual:
    pk: str = theorydb_field(name="PK", roles=["pk"])
    sk: str = theorydb_field(name="SK", roles=["sk"])
    status: str = theorydb_field(name="status", omitempty=True, default="")
    pinned_release_id: str = theorydb_field(name="pinnedReleaseId", omitempty=True, default="")
    previous_release_id: str = theorydb_field(name="previousReleaseId", omitempty=True, default="")
    provenance: dict[str, Any] = theorydb_field(name="provenance", omitempty=True, json=True, default_factory=dict)
    confidence: dict[str, Any] = theorydb_field(name="confidence", omitempty=True, json=True, default_factory=dict)
    updated_at: str = theorydb_field(name="updatedAt", roles=["updated_at"], default="")
    version: int = theorydb_field(name="version", roles=["version"], default=0)


ReleaseStateActualDefinition = ModelDefinition.from_dataclass(
    ReleaseStateActual,
    table_name="release_state_contract",
    write_policy=WritePolicy(mode="mutable", protected_attributes=("pinnedReleaseId",)),
)

@dataclass(frozen=True)
class ReleaseStateEvent:
    pk: str = theorydb_field(name="PK", roles=["pk"])
    sk: str = theorydb_field(name="SK", roles=["sk"])
    release_id: str = theorydb_field(name="releaseId", omitempty=True, default="")
    event_type: str = theorydb_field(name="eventType", omitempty=True, default="")
    provenance: dict[str, Any] = theorydb_field(name="provenance", omitempty=True, json=True, default_factory=dict)
    confidence: dict[str, Any] = theorydb_field(name="confidence", omitempty=True, json=True, default_factory=dict)
    recorded_at: str = theorydb_field(name="recordedAt", omitempty=True, default="")
    ttl: int = theorydb_field(name="ttl", roles=["ttl"], omitempty=True, default=0)


ReleaseStateEventDefinition = ModelDefinition.from_dataclass(
    ReleaseStateEvent,
    table_name="release_state_contract",
    write_policy=WritePolicy(mode="write_once", protected_attributes=()),
)
