# Code generated by tabletheory gen --lang py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass

from theorydb_py import ModelDefinition, theorydb_field


@dataclass(frozen=True)
class SnakeCaseRecord:
    pk: str = theorydb_field(name="pk", roles=["pk"])
    sk: str = theorydb_field(name="sk", roles=["sk"])
    display_name: str = theorydb_field(name="display_name", default="")
    email_hash: str = theorydb_field(name="email_hash", default="")


SnakeCaseRecordDefinition = ModelDefinition.from_dataclass(
    SnakeCaseRecord,
    table_name="snake_case_contract",
)
