# Code generated by tabletheory gen --lang py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from tabletheory_py import ModelDefinition, theorydb_field


@dataclass(frozen=True)
class TypeMatrix:
    pk: str = theorydb_field(name="PK", roles=["pk"])
    sk: str = theorydb_field(name="SK", roles=["sk"])
    number_set: set[int] = theorydb_field(name="numberSet", set_=True, default_factory=set)
    binary_blob: bytes = theorydb_field(name="binaryBlob", default=b"")
    binary_set: set[bytes] = theorydb_field(name="binarySet", set_=True, default_factory=set)
    flag: bool = theorydb_field(name="flag", default=False)
    nothing: None = theorydb_field(name="nothing", default=None)
    items: list[Any] = theorydb_field(name="items", default_factory=list)
    metadata: dict[str, Any] = theorydb_field(name="metadata", default_factory=dict)
    empty_number_set: set[int] = theorydb_field(name="emptyNumberSet", set_=True, default_factory=set)
    empty_binary_set: set[bytes] = theorydb_field(name="emptyBinarySet", set_=True, default_factory=set)
    optional_string: str = theorydb_field(name="optionalString", default="")


TypeMatrixDefinition = ModelDefinition.from_dataclass(
    TypeMatrix,
    table_name="type_matrix_contract",
)
