# Code generated by tabletheory gen --lang py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass

from tabletheory_py import ModelDefinition, Projection, gsi, theorydb_field


@dataclass(frozen=True)
class User:
    pk: str = theorydb_field(name="PK", roles=["pk"])
    sk: str = theorydb_field(name="SK", roles=["sk"])
    email_hash: str = theorydb_field(name="emailHash", omitempty=True, default="")
    nickname: str = theorydb_field(name="nickname", omitempty=True, default="")
    tags: set[str] = theorydb_field(name="tags", omitempty=True, set_=True, default_factory=set)
    created_at: str = theorydb_field(name="createdAt", roles=["created_at"], default="")
    updated_at: str = theorydb_field(name="updatedAt", roles=["updated_at"], default="")
    version: int = theorydb_field(name="version", roles=["version"], default=0)
    ttl: int = theorydb_field(name="ttl", roles=["ttl"], omitempty=True, default=0)


UserDefinition = ModelDefinition.from_dataclass(
    User,
    table_name="users_contract",
    indexes=[
        gsi(
            "gsi-email",
            partition="email_hash",
            projection=Projection.keys_only(),
        ),
    ],
)
