#!/usr/bin/env python3
"""Create/update the deterministic stable Release PR from pending RC state.

This script is intentionally not a release-please wrapper. In the single-manifest
lane, a premain -> main promotion leaves main in pending stable promotion with a
manifest like 2.0.1-rc.1. The stable Release PR is a deterministic normalization
of that repository state to 2.0.1 on the generated release branch.
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import json
import os
import re
import subprocess
import sys
import urllib.parse
from pathlib import Path

SEMVER_RE = re.compile(r"^(?P<base>\d+\.\d+\.\d+)(?P<pre>-rc(?:\.\d+)?)?(?:\+[0-9A-Za-z.-]+)?$")
VERSION_HEADER_RE = re.compile(r"^## \[[0-9]+\.[0-9]+\.[0-9]+(?:-[^\]]+)?\]", re.MULTILINE)
PENDING_RELEASE_LABEL = "autorelease: pending"


def run(
    args: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    input_text: str | None = None,
    capture: bool = False,
    check: bool = True,
    display_args: list[str] | None = None,
) -> str:
    completed = subprocess.run(
        args,
        cwd=cwd,
        env=env,
        input=input_text,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
        check=False,
    )
    if check and completed.returncode != 0:
        if capture:
            sys.stderr.write(completed.stdout)
            sys.stderr.write(completed.stderr)
        safe_args = display_args or args
        raise SystemExit(f"stable-release-pr: FAIL ({' '.join(safe_args)} exited {completed.returncode})")
    return completed.stdout if capture else ""


def fail(message: str) -> None:
    raise SystemExit(f"stable-release-pr: FAIL ({message})")


def read_manifest(repo_root: Path) -> str:
    path = repo_root / ".release-please-manifest.json"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f".release-please-manifest.json is malformed: {exc}")
    version = data.get(".", "") if isinstance(data, dict) else ""
    if not isinstance(version, str) or not version:
        fail(".release-please-manifest.json is missing package '.' version")
    return version


def stable_base(version: str) -> str:
    match = SEMVER_RE.match(version)
    if not match:
        fail(f"manifest version is not supported semver/RC syntax: {version}")
    if not match.group("pre"):
        fail(f"manifest version is already stable: {version}")
    return match.group("base")


def manifest_text(version: str) -> str:
    return json.dumps({".": version}, indent=2) + "\n"


def write_manifest(repo_root: Path, version: str) -> None:
    (repo_root / ".release-please-manifest.json").write_text(manifest_text(version), encoding="utf-8")


def stable_changelog_section(repo: str, rc_version: str, version: str, today: str) -> str:
    return (
        f"## [{version}](https://github.com/{repo}/compare/v{rc_version}...v{version}) ({today})\n"
        "\n"
        f"Stable promotion of `v{rc_version}`.\n"
        "\n"
    )


def stable_pull_request_body(repo: str, rc_version: str, version: str, today: str) -> str:
    notes = stable_changelog_section(repo, rc_version, version, today).rstrip()
    return (
        ":robot: I have created a release *beep* *boop*\n"
        "---\n"
        "\n"
        "\n"
        f"{notes}\n"
        "\n"
        "---\n"
        "\n"
        "This PR was generated by TableTheory release-pr.yml in the Release Please-compatible "
        "stable release format. It normalizes the already-published RC to stable without relying "
        "on promotion merge commit text.\n"
    )


def updated_changelog_text(text: str, repo: str, rc_version: str, version: str, today: str) -> str:
    section = stable_changelog_section(repo, rc_version, version, today)
    stable_header = re.compile(rf"^## \[{re.escape(version)}\].*$", re.MULTILINE)

    match = stable_header.search(text)
    if match:
        line_end = text.find("\n", match.start())
        if line_end == -1:
            line_end = len(text)
        return text[: match.start()] + section.rstrip("\n") + text[line_end:]

    unreleased = re.search(r"^## Unreleased\s*$", text, re.MULTILINE)
    if not unreleased:
        fail("CHANGELOG.md is missing '## Unreleased' section")

    next_version = VERSION_HEADER_RE.search(text, unreleased.end())
    if not next_version:
        fail("CHANGELOG.md is missing an existing version section after Unreleased")

    insert_at = next_version.start()
    prefix = text[:insert_at].rstrip() + "\n\n"
    suffix = text[insert_at:].lstrip("\n")
    return prefix + section + "\n" + suffix


def write_changelog(repo_root: Path, repo: str, rc_version: str, version: str, today: str) -> None:
    path = repo_root / "CHANGELOG.md"
    path.write_text(
        updated_changelog_text(path.read_text(encoding="utf-8"), repo, rc_version, version, today),
        encoding="utf-8",
    )


def ensure_git_identity(repo_root: Path) -> None:
    name = run(["git", "config", "--get", "user.name"], cwd=repo_root, capture=True, check=False).strip()
    email = run(["git", "config", "--get", "user.email"], cwd=repo_root, capture=True, check=False).strip()
    if not name:
        run(["git", "config", "user.name", "github-actions[bot]"], cwd=repo_root)
    if not email:
        run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"], cwd=repo_root)


def git_status(repo_root: Path) -> str:
    return run(["git", "status", "--porcelain"], cwd=repo_root, capture=True)


def git_sha(repo_root: Path, rev: str) -> str:
    sha = run(["git", "rev-parse", "--verify", rev], cwd=repo_root, capture=True).strip()
    if not re.fullmatch(r"[0-9a-f]{40}", sha):
        fail(f"could not resolve git revision {rev}")
    return sha


def gh_api_json(
    repo_root: Path,
    args: list[str],
    *,
    payload: dict[str, object] | None = None,
    check: bool = True,
) -> dict[str, object] | None:
    completed = subprocess.run(
        ["gh", "api", *args],
        cwd=repo_root,
        input=json.dumps(payload) if payload is not None else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        if check:
            sys.stderr.write(completed.stdout)
            sys.stderr.write(completed.stderr)
            raise SystemExit(f"stable-release-pr: FAIL (gh api {' '.join(args)} exited {completed.returncode})")
        return None
    if not completed.stdout.strip():
        return {}
    try:
        parsed = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        fail(f"gh api {' '.join(args)} returned malformed JSON: {exc}")
    if not isinstance(parsed, dict):
        fail(f"gh api {' '.join(args)} returned non-object JSON")
    return parsed


def gh_graphql(repo_root: Path, query: str, variables: dict[str, object]) -> dict[str, object]:
    parsed = gh_api_json(
        repo_root,
        ["graphql", "--input", "-"],
        payload={"query": query, "variables": variables},
    )
    assert parsed is not None
    errors = parsed.get("errors")
    if errors:
        fail(f"GitHub GraphQL mutation failed: {json.dumps(errors, sort_keys=True)}")
    data = parsed.get("data")
    if not isinstance(data, dict):
        fail("GitHub GraphQL response did not contain data")
    return data


def github_ref_sha(repo_root: Path, repo: str, branch: str, *, required: bool) -> str | None:
    parsed = gh_api_json(repo_root, [f"repos/{repo}/git/ref/heads/{branch}"], check=required)
    if parsed is None:
        return None
    obj = parsed.get("object")
    sha = obj.get("sha") if isinstance(obj, dict) else None
    if not isinstance(sha, str) or not re.fullmatch(r"[0-9a-f]{40}", sha):
        fail(f"could not read refs/heads/{branch} from GitHub")
    return sha


def github_commit_verification(repo_root: Path, repo: str, sha: str) -> tuple[bool, str, list[str]]:
    commit_details = gh_api_json(repo_root, [f"repos/{repo}/commits/{sha}"])
    assert commit_details is not None
    commit = commit_details.get("commit")
    verification = commit.get("verification", {}) if isinstance(commit, dict) else {}
    parents = [parent.get("sha", "") for parent in commit_details.get("parents", []) if isinstance(parent, dict)]
    verified = bool(isinstance(verification, dict) and verification.get("verified"))
    reason = str(verification.get("reason", "unknown")) if isinstance(verification, dict) else "unknown"
    return verified, reason, parents


def github_file_text(repo_root: Path, repo: str, path: str, ref: str) -> str:
    encoded_path = urllib.parse.quote(path, safe="")
    parsed = gh_api_json(repo_root, [f"repos/{repo}/contents/{encoded_path}?ref={ref}"])
    assert parsed is not None
    if parsed.get("encoding") != "base64" or not isinstance(parsed.get("content"), str):
        fail(f"could not read {path} from refs/heads/{ref}")
    return base64.b64decode(parsed["content"]).decode("utf-8")


def existing_signed_branch_match(
    repo_root: Path,
    repo: str,
    head: str,
    base_sha: str,
    files: dict[str, str],
) -> str | None:
    current = github_ref_sha(repo_root, repo, head, required=False)
    if current is None:
        return None

    verified, reason, parents = github_commit_verification(repo_root, repo, current)
    if not verified:
        print(f"stable-release-pr: replacing unsigned generated branch {head} ({current[:7]}: {reason})")
        return None
    if parents != [base_sha]:
        print(f"stable-release-pr: replacing generated branch {head} because parent does not match live base")
        return None

    for path, expected in files.items():
        if github_file_text(repo_root, repo, path, head) != expected:
            print(f"stable-release-pr: replacing generated branch {head} because {path} is stale")
            return None

    print(f"stable-release-pr: existing GitHub-signed commit {current[:7]} already normalizes {head}")
    return current


def create_or_reset_branch(repo_root: Path, repo: str, branch: str, sha: str) -> None:
    current = github_ref_sha(repo_root, repo, branch, required=False)
    if current == sha:
        return
    if current is None:
        gh_api_json(
            repo_root,
            ["--method", "POST", f"repos/{repo}/git/refs", "--input", "-"],
            payload={"ref": f"refs/heads/{branch}", "sha": sha},
        )
    else:
        gh_api_json(
            repo_root,
            ["--method", "PATCH", f"repos/{repo}/git/refs/heads/{branch}", "--input", "-"],
            payload={"sha": sha, "force": True},
        )
    updated = github_ref_sha(repo_root, repo, branch, required=True)
    if updated != sha:
        fail(f"refs/heads/{branch} did not reset to expected base {sha}")


def create_github_signed_commit_on_branch(
    repo_root: Path,
    repo: str,
    base: str,
    head: str,
    title: str,
    files: dict[str, str],
) -> str:
    base_sha = github_ref_sha(repo_root, repo, base, required=True)
    local_head = git_sha(repo_root, "HEAD")
    if base_sha != local_head:
        fail(f"checked-out HEAD {local_head} does not match live refs/heads/{base} {base_sha}")

    existing = existing_signed_branch_match(repo_root, repo, head, base_sha, files)
    if existing is not None:
        return existing

    # Reset the generated release branch to the live base before asking GitHub to
    # create the release commit. This replaces any earlier unsigned/generated
    # commit instead of appending a signed commit on top of it.
    create_or_reset_branch(repo_root, repo, head, base_sha)

    additions = [
        {
            "path": path,
            "contents": base64.b64encode(content.encode("utf-8")).decode("ascii"),
        }
        for path, content in files.items()
    ]
    query = """
mutation CreateStableReleaseCommit($input: CreateCommitOnBranchInput!) {
  createCommitOnBranch(input: $input) {
    commit {
      oid
    }
  }
}
"""
    data = gh_graphql(
        repo_root,
        query,
        {
            "input": {
                "branch": {"repositoryNameWithOwner": repo, "branchName": head},
                "message": {"headline": title},
                "fileChanges": {"additions": additions},
                "expectedHeadOid": base_sha,
            }
        },
    )
    payload = data.get("createCommitOnBranch")
    commit = payload.get("commit") if isinstance(payload, dict) else None
    commit_sha = commit.get("oid") if isinstance(commit, dict) else None
    if not isinstance(commit_sha, str) or not re.fullmatch(r"[0-9a-f]{40}", commit_sha):
        fail("GitHub GraphQL response did not include the created commit SHA")

    branch_sha = github_ref_sha(repo_root, repo, head, required=True)
    if branch_sha != commit_sha:
        fail(f"refs/heads/{head} moved unexpectedly after GitHub commit creation")

    verified, reason, _parents = github_commit_verification(repo_root, repo, commit_sha)
    if not verified:
        fail(f"GitHub did not report a verified signature for generated commit {commit_sha}: {reason}")

    print(f"stable-release-pr: GitHub-signed commit {commit_sha[:7]} created on {head}")
    return commit_sha


def ensure_pending_label(repo_root: Path, repo: str) -> None:
    labels = run(
        ["gh", "label", "list", "--repo", repo, "--search", PENDING_RELEASE_LABEL, "--json", "name", "--limit", "100"],
        cwd=repo_root,
        capture=True,
    )
    parsed = json.loads(labels)
    if any(label.get("name") == PENDING_RELEASE_LABEL for label in parsed):
        return
    run(
        [
            "gh",
            "label",
            "create",
            PENDING_RELEASE_LABEL,
            "--repo",
            repo,
            "--color",
            "ededed",
            "--description",
            "Release Please pending release",
        ],
        cwd=repo_root,
    )


def upsert_pr(repo_root: Path, repo: str, base: str, head: str, title: str, body: str) -> None:
    ensure_pending_label(repo_root, repo)
    existing = run(
        ["gh", "pr", "list", "--repo", repo, "--base", base, "--head", head, "--state", "open", "--json", "number"],
        cwd=repo_root,
        capture=True,
    )
    prs = json.loads(existing)
    if prs:
        number = str(prs[0]["number"])
        run(["gh", "pr", "edit", number, "--repo", repo, "--title", title, "--body", body], cwd=repo_root)
        run(["gh", "pr", "edit", number, "--repo", repo, "--add-label", PENDING_RELEASE_LABEL], cwd=repo_root)
        print(f"stable-release-pr: updated PR #{number} ({title})")
    else:
        run(
            [
                "gh",
                "pr",
                "create",
                "--repo",
                repo,
                "--base",
                base,
                "--head",
                head,
                "--title",
                title,
                "--body",
                body,
                "--label",
                PENDING_RELEASE_LABEL,
            ],
            cwd=repo_root,
        )
        print(f"stable-release-pr: opened PR ({title})")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "theory-cloud/TableTheory"))
    parser.add_argument("--base", default="main")
    parser.add_argument("--head", default="release-please--branches--main")
    parser.add_argument("--expected-version", required=True)
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    expected = args.expected_version
    if not re.match(r"^\d+\.\d+\.\d+$", expected):
        fail(f"expected version must be stable X.Y.Z, got {expected}")

    rc_version = read_manifest(repo_root)
    computed = stable_base(rc_version)
    if computed != expected:
        fail(f"computed stable version {computed} from {rc_version}, expected {expected}")

    today = os.environ.get("RELEASE_DATE") or dt.datetime.now(dt.timezone.utc).date().isoformat()
    title = f"chore({args.base}): release {expected}"
    body = stable_pull_request_body(args.repo, rc_version, expected, today)

    if git_status(repo_root):
        fail("working tree must be clean before generating stable Release PR")

    desired_files = {
        ".release-please-manifest.json": manifest_text(expected),
        "CHANGELOG.md": updated_changelog_text(
            (repo_root / "CHANGELOG.md").read_text(encoding="utf-8"),
            args.repo,
            rc_version,
            expected,
            today,
        ),
    }

    if all((repo_root / path).read_text(encoding="utf-8") == content for path, content in desired_files.items()):
        print(f"stable-release-pr: PASS ({args.head} already normalizes {expected})")
        return 0

    if args.dry_run:
        run(["git", "checkout", "-B", args.head, "HEAD"], cwd=repo_root)
        for path, content in desired_files.items():
            (repo_root / path).write_text(content, encoding="utf-8")
        ensure_git_identity(repo_root)
        run(["git", "add", *desired_files.keys()], cwd=repo_root)
        run(["git", "commit", "-m", title], cwd=repo_root)
        print(f"stable-release-pr: dry-run generated {title} on {args.head}")
        return 0

    create_github_signed_commit_on_branch(repo_root, args.repo, args.base, args.head, title, desired_files)
    upsert_pr(repo_root, args.repo, args.base, args.head, title, body)
    print(f"stable-release-pr: PASS ({args.head} -> {args.base}, version {expected})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
