#!/usr/bin/env python3
"""Create/update the deterministic stable Release PR from pending RC state.

This script is intentionally not a release-please wrapper. In the single-manifest
lane, a premain -> main promotion leaves main in pending stable promotion with a
manifest like 2.0.1-rc.1. The stable Release PR is a deterministic normalization
of that repository state to 2.0.1 on the generated release branch.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import subprocess
import sys
from pathlib import Path

SEMVER_RE = re.compile(r"^(?P<base>\d+\.\d+\.\d+)(?P<pre>-rc(?:\.\d+)?)?(?:\+[0-9A-Za-z.-]+)?$")
VERSION_HEADER_RE = re.compile(r"^## \[[0-9]+\.[0-9]+\.[0-9]+(?:-[^\]]+)?\]", re.MULTILINE)
PENDING_RELEASE_LABEL = "autorelease: pending"


def run(
    args: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    capture: bool = False,
    check: bool = True,
    display_args: list[str] | None = None,
) -> str:
    completed = subprocess.run(
        args,
        cwd=cwd,
        env=env,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
        check=False,
    )
    if check and completed.returncode != 0:
        if capture:
            sys.stderr.write(completed.stdout)
            sys.stderr.write(completed.stderr)
        safe_args = display_args or args
        raise SystemExit(f"stable-release-pr: FAIL ({' '.join(safe_args)} exited {completed.returncode})")
    return completed.stdout if capture else ""


def fail(message: str) -> None:
    raise SystemExit(f"stable-release-pr: FAIL ({message})")


def read_manifest(repo_root: Path) -> str:
    path = repo_root / ".release-please-manifest.json"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f".release-please-manifest.json is malformed: {exc}")
    version = data.get(".", "") if isinstance(data, dict) else ""
    if not isinstance(version, str) or not version:
        fail(".release-please-manifest.json is missing package '.' version")
    return version


def stable_base(version: str) -> str:
    match = SEMVER_RE.match(version)
    if not match:
        fail(f"manifest version is not supported semver/RC syntax: {version}")
    if not match.group("pre"):
        fail(f"manifest version is already stable: {version}")
    return match.group("base")


def write_manifest(repo_root: Path, version: str) -> None:
    (repo_root / ".release-please-manifest.json").write_text(
        json.dumps({".": version}, indent=2) + "\n",
        encoding="utf-8",
    )


def stable_changelog_section(repo: str, rc_version: str, version: str, today: str) -> str:
    return (
        f"## [{version}](https://github.com/{repo}/compare/v{rc_version}...v{version}) ({today})\n"
        "\n"
        f"Stable promotion of `v{rc_version}`.\n"
        "\n"
    )


def stable_pull_request_body(repo: str, rc_version: str, version: str, today: str) -> str:
    notes = stable_changelog_section(repo, rc_version, version, today).rstrip()
    return (
        ":robot: I have created a release *beep* *boop*\n"
        "---\n"
        "\n"
        "\n"
        f"{notes}\n"
        "\n"
        "---\n"
        "\n"
        "This PR was generated by TableTheory release-pr.yml in the Release Please-compatible "
        "stable release format. It normalizes the already-published RC to stable without relying "
        "on promotion merge commit text.\n"
    )


def write_changelog(repo_root: Path, repo: str, rc_version: str, version: str, today: str) -> None:
    path = repo_root / "CHANGELOG.md"
    text = path.read_text(encoding="utf-8")
    section = stable_changelog_section(repo, rc_version, version, today)
    stable_header = re.compile(rf"^## \[{re.escape(version)}\].*$", re.MULTILINE)

    match = stable_header.search(text)
    if match:
        line_end = text.find("\n", match.start())
        if line_end == -1:
            line_end = len(text)
        text = text[: match.start()] + section.rstrip("\n") + text[line_end:]
        path.write_text(text, encoding="utf-8")
        return

    unreleased = re.search(r"^## Unreleased\s*$", text, re.MULTILINE)
    if not unreleased:
        fail("CHANGELOG.md is missing '## Unreleased' section")

    next_version = VERSION_HEADER_RE.search(text, unreleased.end())
    if not next_version:
        fail("CHANGELOG.md is missing an existing version section after Unreleased")

    insert_at = next_version.start()
    prefix = text[:insert_at].rstrip() + "\n\n"
    suffix = text[insert_at:].lstrip("\n")
    path.write_text(prefix + section + "\n" + suffix, encoding="utf-8")


def ensure_git_identity(repo_root: Path) -> None:
    name = run(["git", "config", "--get", "user.name"], cwd=repo_root, capture=True, check=False).strip()
    email = run(["git", "config", "--get", "user.email"], cwd=repo_root, capture=True, check=False).strip()
    if not name:
        run(["git", "config", "user.name", "github-actions[bot]"], cwd=repo_root)
    if not email:
        run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"], cwd=repo_root)


def git_status(repo_root: Path) -> str:
    return run(["git", "status", "--porcelain"], cwd=repo_root, capture=True)


def authenticated_remote(repo: str, token: str) -> str:
    return f"https://x-access-token:{token}@github.com/{repo}.git"


def branch_lease(repo_root: Path, remote: str, head: str) -> str:
    output = run(
        ["git", "ls-remote", "--heads", remote, head],
        cwd=repo_root,
        capture=True,
        display_args=["git", "ls-remote", "--heads", "https://github.com/OWNER/REPO.git", head],
    ).strip()
    if not output:
        return f"--force-with-lease=refs/heads/{head}:"
    first_line = output.splitlines()[0]
    sha = first_line.split()[0]
    if not re.fullmatch(r"[0-9a-f]{40}", sha):
        fail(f"could not read current remote head SHA for {head}")
    return f"--force-with-lease=refs/heads/{head}:{sha}"


def ensure_pending_label(repo_root: Path, repo: str) -> None:
    labels = run(
        ["gh", "label", "list", "--repo", repo, "--search", PENDING_RELEASE_LABEL, "--json", "name", "--limit", "100"],
        cwd=repo_root,
        capture=True,
    )
    parsed = json.loads(labels)
    if any(label.get("name") == PENDING_RELEASE_LABEL for label in parsed):
        return
    run(
        [
            "gh",
            "label",
            "create",
            PENDING_RELEASE_LABEL,
            "--repo",
            repo,
            "--color",
            "ededed",
            "--description",
            "Release Please pending release",
        ],
        cwd=repo_root,
    )


def upsert_pr(repo_root: Path, repo: str, base: str, head: str, title: str, body: str) -> None:
    ensure_pending_label(repo_root, repo)
    existing = run(
        ["gh", "pr", "list", "--repo", repo, "--base", base, "--head", head, "--state", "open", "--json", "number"],
        cwd=repo_root,
        capture=True,
    )
    prs = json.loads(existing)
    if prs:
        number = str(prs[0]["number"])
        run(["gh", "pr", "edit", number, "--repo", repo, "--title", title, "--body", body], cwd=repo_root)
        run(["gh", "pr", "edit", number, "--repo", repo, "--add-label", PENDING_RELEASE_LABEL], cwd=repo_root)
        print(f"stable-release-pr: updated PR #{number} ({title})")
    else:
        run(
            [
                "gh",
                "pr",
                "create",
                "--repo",
                repo,
                "--base",
                base,
                "--head",
                head,
                "--title",
                title,
                "--body",
                body,
                "--label",
                PENDING_RELEASE_LABEL,
            ],
            cwd=repo_root,
        )
        print(f"stable-release-pr: opened PR ({title})")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "theory-cloud/TableTheory"))
    parser.add_argument("--base", default="main")
    parser.add_argument("--head", default="release-please--branches--main")
    parser.add_argument("--expected-version", required=True)
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    expected = args.expected_version
    if not re.match(r"^\d+\.\d+\.\d+$", expected):
        fail(f"expected version must be stable X.Y.Z, got {expected}")

    rc_version = read_manifest(repo_root)
    computed = stable_base(rc_version)
    if computed != expected:
        fail(f"computed stable version {computed} from {rc_version}, expected {expected}")

    today = os.environ.get("RELEASE_DATE") or dt.datetime.now(dt.timezone.utc).date().isoformat()
    title = f"chore({args.base}): release {expected}"
    body = stable_pull_request_body(args.repo, rc_version, expected, today)

    if git_status(repo_root):
        fail("working tree must be clean before generating stable Release PR")

    run(["git", "checkout", "-B", args.head, "HEAD"], cwd=repo_root)
    write_manifest(repo_root, expected)
    write_changelog(repo_root, args.repo, rc_version, expected, today)

    status = git_status(repo_root)
    if not status:
        print(f"stable-release-pr: PASS ({args.head} already normalizes {expected})")
        return 0

    ensure_git_identity(repo_root)
    run(["git", "add", ".release-please-manifest.json", "CHANGELOG.md"], cwd=repo_root)
    run(["git", "commit", "-m", title], cwd=repo_root)

    if args.dry_run:
        print(f"stable-release-pr: dry-run generated {title} on {args.head}")
        return 0

    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN") or os.environ.get("RELEASE_PLEASE_TOKEN")
    if not token:
        fail("missing GH_TOKEN/GITHUB_TOKEN/RELEASE_PLEASE_TOKEN for branch push and PR upsert")

    remote = authenticated_remote(args.repo, token)
    lease = branch_lease(repo_root, remote, args.head)
    run(
        ["git", "push", remote, f"HEAD:refs/heads/{args.head}", lease],
        cwd=repo_root,
        display_args=["git", "push", f"https://github.com/{args.repo}.git", f"HEAD:refs/heads/{args.head}", lease],
    )
    upsert_pr(repo_root, args.repo, args.base, args.head, title, body)
    print(f"stable-release-pr: PASS ({args.head} -> {args.base}, version {expected})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
