#!/usr/bin/env python3
"""Generate TableTheory API reference markdown from source artifacts.

Go uses `go doc -short` over public packages. TypeScript uses declaration files
emitted from `ts/src` by `npm run build:esm`. Python uses the AST of
`py/src/tabletheory_py` and the package `__all__` export list. The generated docs
are committed and this script provides the drift gate.
"""
from __future__ import annotations

import argparse
import ast
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


GENERATED = "<!-- Code generated by scripts/generate-api-reference.py; DO NOT EDIT. -->"

GO_PACKAGES = (
    "github.com/theory-cloud/tabletheory",
    "github.com/theory-cloud/tabletheory/pkg/core",
    "github.com/theory-cloud/tabletheory/pkg/model",
    "github.com/theory-cloud/tabletheory/pkg/query",
    "github.com/theory-cloud/tabletheory/pkg/session",
    "github.com/theory-cloud/tabletheory/pkg/types",
    "github.com/theory-cloud/tabletheory/pkg/marshal",
    "github.com/theory-cloud/tabletheory/pkg/transaction",
    "github.com/theory-cloud/tabletheory/pkg/errors",
    "github.com/theory-cloud/tabletheory/pkg/mocks",
    "github.com/theory-cloud/tabletheory/pkg/typed",
    "github.com/theory-cloud/tabletheory/pkg/testing",
    "github.com/theory-cloud/tabletheory/pkg/testing/fakedb",
    "github.com/theory-cloud/tabletheory/pkg/schema",
    "github.com/theory-cloud/tabletheory/pkg/dms",
)

TS_MODULES = (
    "errors",
    "client",
    "cursor",
    "dms",
    "model",
    "query",
    "batch",
    "transaction",
    "streams",
    "aggregates",
    "optimizer",
    "encryption",
    "encryption-kms",
    "schema",
    "schema-migration",
    "update-builder",
    "lambda",
    "multiaccount",
    "send-options",
    "validation",
    "protection",
    "write-policy",
    "release-state",
    "lease",
    "facetheory-isr",
    "key-contract",
)


@dataclass(frozen=True)
class PyExport:
    name: str
    module: str
    kind: str
    signature: str
    details: tuple[str, ...] = ()


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def run(cmd: list[str], cwd: Path, env: dict[str, str] | None = None) -> str:
    result = subprocess.run(
        cmd,
        cwd=cwd,
        env=env,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return result.stdout


def go_env(root: Path) -> dict[str, str]:
    env = os.environ.copy()
    for line in (root / "go.mod").read_text(encoding="utf-8").splitlines():
        if line.startswith("toolchain "):
            env.setdefault("GOTOOLCHAIN", line.split()[1])
            break
    return env


def render_go(root: Path) -> str:
    sections: list[str] = [
        "---",
        "title: TableTheory API Reference",
        "---",
        "",
        "# TableTheory API Reference",
        "",
        GENERATED,
        "",
        "This reference is generated from Go source with `go doc -short`. Do not hand-edit signatures here; run `make generate-api-reference`.",
        "",
        "Runtime peers: [TypeScript](./runtimes/typescript/api-reference.md) · [Python](./runtimes/python/api-reference.md)",
        "",
        "## Drift check",
        "",
        "```bash",
        "make verify-api-reference",
        "```",
        "",
        "## Go packages",
        "",
    ]
    env = go_env(root)
    for pkg in GO_PACKAGES:
        doc = run(["go", "doc", "-short", pkg], cwd=root, env=env).strip()
        if not doc:
            continue
        sections.extend([f"### `{pkg}`", "", "```go", doc, "```", ""])
    return "\n".join(sections).rstrip() + "\n"


def build_ts_declarations(root: Path) -> None:
    # `build:esm` emits the declaration files used below without producing CJS-only package metadata.
    run(["npm", "--prefix", "ts", "run", "build:esm"], cwd=root)


def clean_dts(content: str) -> str:
    lines: list[str] = []
    for line in content.splitlines():
        if line.startswith("//# sourceMappingURL="):
            continue
        lines.append(line.rstrip())
    return "\n".join(lines).strip()


def render_ts(root: Path) -> str:
    build_ts_declarations(root)
    sections: list[str] = [
        "# API Reference (TypeScript)",
        "",
        GENERATED,
        "",
        "<!-- prettier-ignore-start -->",
        "",
        "This reference is generated from declaration files emitted from `ts/src`. Do not hand-edit signatures here; run `make generate-api-reference`.",
        "",
        "## Drift check",
        "",
        "```bash",
        "make verify-api-reference",
        "```",
        "",
        "## Public modules",
        "",
    ]
    for module in TS_MODULES:
        path = root / "ts" / "dist" / f"{module}.d.ts"
        if not path.exists():
            raise FileNotFoundError(f"missing TypeScript declaration {path.relative_to(root)}")
        content = clean_dts(path.read_text(encoding="utf-8"))
        if not content:
            continue
        sections.extend([f"### `{module}`", "", "```ts", content, "```", ""])
    sections.extend(["<!-- prettier-ignore-end -->", ""])
    return "\n".join(sections).rstrip() + "\n"


def module_name_from_path(path: Path) -> str:
    return path.stem


def parse_py_exports(root: Path) -> tuple[list[str], dict[str, str]]:
    init_path = root / "py" / "src" / "tabletheory_py" / "__init__.py"
    tree = ast.parse(init_path.read_text(encoding="utf-8"), filename=str(init_path))
    exports: list[str] = []
    import_map: dict[str, str] = {}

    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module and node.level == 1:
            module = node.module
            for alias in node.names:
                if alias.name == "*":
                    continue
                public_name = alias.asname or alias.name
                import_map[public_name] = module
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__" and isinstance(node.value, ast.List):
                    for elt in node.value.elts:
                        if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                            exports.append(elt.value)
    if not exports:
        raise RuntimeError("could not parse tabletheory_py.__all__")
    return exports, import_map


def annotation_text(node: ast.AST | None) -> str:
    if node is None:
        return "Any"
    return ast.unparse(node)


def function_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    return f"def {node.name}({ast.unparse(node.args)})" + (f" -> {annotation_text(node.returns)}" if node.returns else "")


def class_signature(node: ast.ClassDef) -> str:
    bases = [ast.unparse(base) for base in node.bases]
    suffix = f"({', '.join(bases)})" if bases else ""
    return f"class {node.name}{suffix}"


def collect_py_module(root: Path, module: str) -> dict[str, PyExport]:
    path = root / "py" / "src" / "tabletheory_py" / f"{module}.py"
    if not path.exists():
        return {}
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    found: dict[str, PyExport] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            found[node.name] = PyExport(node.name, module, "function", function_signature(node))
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            details: list[str] = []
            for item in node.body:
                if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name) and not item.target.id.startswith("_"):
                    details.append(f"{item.target.id}: {annotation_text(item.annotation)}")
                elif isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) and not item.name.startswith("_"):
                    details.append(function_signature(item))
            found[node.name] = PyExport(node.name, module, "class", class_signature(node), tuple(details))
    return found


def render_py(root: Path) -> str:
    exports, import_map = parse_py_exports(root)
    modules: dict[str, dict[str, PyExport]] = {}
    for module in sorted(set(import_map.values())):
        modules[module] = collect_py_module(root, module)

    by_module: dict[str, list[PyExport]] = {}
    missing: list[str] = []
    for name in exports:
        if name.startswith("__"):
            continue
        module = import_map.get(name)
        if module is None:
            missing.append(name)
            continue
        export = modules.get(module, {}).get(name)
        if export is None:
            missing.append(name)
            continue
        by_module.setdefault(module, []).append(export)

    sections: list[str] = [
        "# API Reference (Python)",
        "",
        GENERATED,
        "",
        "This reference is generated from `py/src/tabletheory_py` source and the package `__all__` export list. Do not hand-edit signatures here; run `make generate-api-reference`.",
        "",
        "## Drift check",
        "",
        "```bash",
        "make verify-api-reference",
        "```",
        "",
        "## Public exports",
        "",
    ]
    for module in sorted(by_module):
        sections.extend([f"### `tabletheory_py.{module}`", ""])
        for export in sorted(by_module[module], key=lambda e: e.name.lower()):
            sections.extend([f"#### `{export.name}`", "", "```python", export.signature])
            if export.details:
                sections.extend([*export.details])
            sections.extend(["```", ""])
    if missing:
        sections.extend([
            "## Re-exported values without source signatures",
            "",
            "These names are exported constants, aliases, or lazy imports that do not have a direct function/class signature:",
            "",
            ", ".join(f"`{name}`" for name in sorted(missing)),
            "",
        ])
    return "\n".join(sections).rstrip() + "\n"


def generated_docs(root: Path) -> dict[Path, str]:
    return {
        root / "docs" / "api-reference.md": render_go(root),
        root / "ts" / "docs" / "api-reference.md": render_ts(root),
        root / "py" / "docs" / "api-reference.md": render_py(root),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write generated API references")
    parser.add_argument("--check", action="store_true", help="fail when generated API references are stale")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("choose exactly one of --write or --check")

    root = repo_root()
    docs = generated_docs(root)
    stale: list[str] = []
    for path, expected in docs.items():
        if args.write:
            path.write_text(expected, encoding="utf-8")
            continue
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            stale.append(path.relative_to(root).as_posix())

    if stale:
        print("api-reference: FAIL stale generated reference(s):", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        print("regenerate with: make generate-api-reference", file=sys.stderr)
        return 1

    print("api-reference: wrote" if args.write else "api-reference: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
