#!/usr/bin/env python3
"""Sync package-local TypeScript/Python docs into the Jekyll site source.

The package docs remain the authoring source of truth because they ship inside
release artifacts. The site copies are generated with front matter and checked
for drift so TS/Py runtime docs are first-class Jekyll pages without hand-copy
signature drift.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class RuntimeDoc:
    runtime: str
    label: str
    source: Path
    dest: Path
    title: str
    description: str


DOC_NAMES = (
    ("getting-started.md", "Getting Started", "install and run the first local CRUD flow"),
    ("api-reference.md", "API Reference", "public API signatures and option shapes"),
    ("core-patterns.md", "Core Patterns", "canonical CRUD, query, transaction, and testing recipes"),
    ("testing-guide.md", "Testing Guide", "unit, fake-backed, and DynamoDB Local test patterns"),
    ("troubleshooting.md", "Troubleshooting", "runtime-native fixes for common errors"),
    ("migration-guide.md", "Migration Guide", "moving from raw AWS SDK usage to TableTheory"),
    ("release-state.md", "Release-State Patterns", "release-state write-policy and transition recipes"),
)

RUNTIMES = (
    ("typescript", "TypeScript", Path("ts/docs"), Path("docs/runtimes/typescript")),
    ("python", "Python", Path("py/docs"), Path("docs/runtimes/python")),
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def iter_docs(root: Path) -> list[RuntimeDoc]:
    docs: list[RuntimeDoc] = []
    for runtime, label, source_dir, dest_dir in RUNTIMES:
        for filename, title, summary in DOC_NAMES:
            source = source_dir / filename
            dest = dest_dir / filename
            docs.append(
                RuntimeDoc(
                    runtime=runtime,
                    label=label,
                    source=root / source,
                    dest=root / dest,
                    title=f"{label} {title}",
                    description=f"TableTheory {label} runtime {summary}.",
                )
            )
    return docs


def render(doc: RuntimeDoc, root: Path) -> str:
    if not doc.source.exists():
        raise FileNotFoundError(f"missing source doc {doc.source.relative_to(root)}")
    body = doc.source.read_text(encoding="utf-8")
    body = body.rstrip() + "\n"
    rel_source = doc.source.relative_to(root).as_posix()
    return (
        "---\n"
        f"title: {doc.title}\n"
        f"description: {doc.description}\n"
        f"runtime: {doc.runtime}\n"
        f"source_doc: {rel_source}\n"
        "generated: true\n"
        "---\n\n"
        "<!-- Code generated by scripts/sync-runtime-docs-site.py; DO NOT EDIT. -->\n"
        f"<!-- Source: {rel_source} -->\n\n"
        f"[Package-source copy](https://github.com/theory-cloud/TableTheory/blob/main/{rel_source}) · "
        "Generated into the site so runtime docs are searchable and linkable.\n\n"
        + body
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write generated site docs")
    parser.add_argument("--check", action="store_true", help="fail if generated site docs are stale")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("choose exactly one of --write or --check")

    root = repo_root()
    stale: list[str] = []
    for doc in iter_docs(root):
        expected = render(doc, root)
        if args.write:
            doc.dest.parent.mkdir(parents=True, exist_ok=True)
            doc.dest.write_text(expected, encoding="utf-8")
            continue
        actual = doc.dest.read_text(encoding="utf-8") if doc.dest.exists() else None
        if actual != expected:
            stale.append(doc.dest.relative_to(root).as_posix())

    if stale:
        print("runtime-docs-site: FAIL stale generated site doc(s):", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        print("regenerate with: python3 scripts/sync-runtime-docs-site.py --write", file=sys.stderr)
        return 1

    action = "wrote" if args.write else "PASS"
    print(f"runtime-docs-site: {action}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
