#!/usr/bin/env bash
set -euo pipefail

mode="${1:---check}"
case "${mode}" in
  --check|--write) ;;
  *)
    echo "usage: $0 [--check|--write]" >&2
    exit 2
    ;;
esac

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

specs=(
  "user"
  "order"
  "number-precision"
  "type-matrix"
  "snake-case-record"
  "encrypted-record"
  "release-state"
)

go_dir="contract-tests/runners/go/internal/driver"
py_dir="contract-tests/runners/py/generated_models"

generate_into() {
  local root="$1"
  mkdir -p "${root}/${go_dir}" "${root}/${py_dir}"

  for name in "${specs[@]}"; do
    local dms_path="contract-tests/dms/v0.1/models/${name}.yml"
    go run ./cmd/tabletheory gen --lang go --package driver \
      --out "${root}/${go_dir}/models_${name//-/_}_generated.go" \
      "${dms_path}"
    go run ./cmd/tabletheory gen --lang py \
      --out "${root}/${py_dir}/${name//-/_}.py" \
      "${dms_path}"
  done

  cat > "${root}/${py_dir}/__init__.py" <<'PY'
# Code generated by scripts/verify-generated-models.sh; DO NOT EDIT.
from __future__ import annotations

from .encrypted_record import EncryptedRecord, EncryptedRecordDefinition
from .number_precision import NumberPrecision, NumberPrecisionDefinition
from .order import Order, OrderDefinition
from .release_state import (
    ReleaseStateActual,
    ReleaseStateActualDefinition,
    ReleaseStateEvent,
    ReleaseStateEventDefinition,
)
from .snake_case_record import SnakeCaseRecord, SnakeCaseRecordDefinition
from .type_matrix import TypeMatrix, TypeMatrixDefinition
from .user import User, UserDefinition

__all__ = [
    "EncryptedRecord",
    "EncryptedRecordDefinition",
    "NumberPrecision",
    "NumberPrecisionDefinition",
    "Order",
    "OrderDefinition",
    "ReleaseStateActual",
    "ReleaseStateActualDefinition",
    "ReleaseStateEvent",
    "ReleaseStateEventDefinition",
    "SnakeCaseRecord",
    "SnakeCaseRecordDefinition",
    "TypeMatrix",
    "TypeMatrixDefinition",
    "User",
    "UserDefinition",
]
PY
}

assert_no_hand_authored_contract_models() {
  if grep -Eq '^type (User|Order|NumberPrecision|TypeMatrix|SnakeCaseRecord|EncryptedRecord|ReleaseStateActual|ReleaseStateEvent) struct' \
      contract-tests/runners/go/internal/driver/driver.go; then
    echo "generated-models: FAIL hand-authored Go contract model remains in driver.go" >&2
    return 1
  fi
  if grep -Eq '^class _(User|Order|NumberPrecision|TypeMatrix|SnakeCaseRecord|EncryptedRecord|ReleaseStateActual|ReleaseStateEvent)\b' \
      contract-tests/runners/py/test_contract_p0.py; then
    echo "generated-models: FAIL hand-authored Python contract model remains in test_contract_p0.py" >&2
    return 1
  fi
}

if [[ "${mode}" == "--write" ]]; then
  generate_into "."
  assert_no_hand_authored_contract_models
  echo "generated-models: wrote Go/Python contract runner models"
  exit 0
fi

tmp="$(mktemp -d)"
cleanup() { rm -rf "${tmp}"; }
trap cleanup EXIT

generate_into "${tmp}"

status=0
for rel in "${go_dir}"/models_*_generated.go "${py_dir}"/*.py; do
  if [[ ! -f "${rel}" ]]; then
    echo "generated-models: FAIL missing committed generated file ${rel}" >&2
    status=1
    continue
  fi
  if ! diff -u "${tmp}/${rel}" "${rel}"; then
    echo "generated-models: FAIL ${rel} is stale" >&2
    status=1
  fi
done

if ! assert_no_hand_authored_contract_models; then
  status=1
fi

if [[ "${status}" -ne 0 ]]; then
  echo "generated-models: regenerate with: bash scripts/verify-generated-models.sh --write" >&2
  exit "${status}"
fi

echo "generated-models: PASS"
