// Code generated by tabletheory gen --lang ts; DO NOT EDIT.
import { defineModel } from '../../../src/index.js';

export const DMSNoteSchema = {
  name: 'DMSNote',
  table: {
    name: 'dms_notes',
  },
  naming: {
    convention: 'camelCase',
  },
  keys: {
    partition: {
      attribute: 'PK',
      type: 'S',
    },
    sort: {
      attribute: 'SK',
      type: 'S',
    },
  },
  write_policy: {
    mode: 'mutable',
    protected_attributes: ['title'],
  },
  attributes: [
    {
      attribute: 'PK',
      type: 'S',
      required: true,
      roles: ['pk'],
    },
    {
      attribute: 'SK',
      type: 'S',
      required: true,
      roles: ['sk'],
    },
    {
      attribute: 'blob',
      type: 'B',
      optional: true,
      binary: true,
    },
    {
      attribute: 'count',
      type: 'N',
      optional: true,
    },
    {
      attribute: 'createdAt',
      type: 'S',
      format: 'rfc3339nano',
      optional: true,
      roles: ['created_at'],
    },
    {
      attribute: 'payload',
      type: 'M',
      optional: true,
      json: true,
    },
    {
      attribute: 'secret',
      type: 'S',
      optional: true,
      omit_empty: true,
      encryption: {
        v: 1,
      },
    },
    {
      attribute: 'tags',
      type: 'SS',
      optional: true,
      omit_empty: true,
    },
    {
      attribute: 'title',
      type: 'S',
      optional: true,
      omit_empty: true,
    },
    {
      attribute: 'ttl',
      type: 'N',
      format: 'unix_seconds',
      optional: true,
      omit_empty: true,
      roles: ['ttl'],
    },
    {
      attribute: 'version',
      type: 'N',
      format: 'int',
      optional: true,
      roles: ['version'],
    },
  ],
  indexes: [
    {
      name: 'gsi-title',
      type: 'GSI',
      partition: {
        attribute: 'title',
        type: 'S',
      },
      sort: {
        attribute: 'createdAt',
        type: 'S',
      },
      projection: {
        type: 'INCLUDE',
        fields: ['count', 'payload'],
      },
    },
  ],
} as const;

export const DMSNoteModel = defineModel(DMSNoteSchema);
