package keycontract

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"
	"unicode"
	"unicode/utf8"
)

// GenerateTypeScriptOptions controls generated TypeScript helper output.
type GenerateTypeScriptOptions struct {
	RuntimeImport string
}

// GenerateTypeScript emits a TypeScript helper module for a sidecar contract.
func GenerateTypeScript(contract *Contract, opts GenerateTypeScriptOptions) (string, error) {
	if contract == nil {
		return "", fmt.Errorf("tabletheory model contract is nil")
	}
	if err := contract.Validate(); err != nil {
		return "", err
	}
	importPath := opts.RuntimeImport
	if importPath == "" {
		importPath = "@theory-cloud/tabletheory-ts"
	}

	jsonBytes, err := MarshalJSONStable(contract)
	if err != nil {
		return "", err
	}

	var out bytes.Buffer
	out.WriteString("// Generated by tabletheory-contract generate-ts; do not edit by hand.\n")
	out.WriteString("import {\n")
	out.WriteString("  evaluateDerivedKey,\n")
	out.WriteString("  type DerivedKeyContract,\n")
	out.WriteString("  type KeyContractInputValue,\n")
	out.WriteString("} from ")
	out.WriteString(quoteTS(importPath))
	out.WriteString(";\n\n")
	out.WriteString("export const tabletheoryModelContract = ")
	out.Write(jsonBytes)
	out.WriteString(" as const satisfies DerivedKeyContract;\n\n")

	for _, key := range contract.DerivedKeys {
		functionName, typeName, err := generatedNames(key)
		if err != nil {
			return "", err
		}
		out.WriteString("export interface ")
		out.WriteString(typeName)
		out.WriteString(" {\n")
		for _, input := range key.Inputs {
			prop := tsPropertyName(input)
			if !isIdentifier(prop) {
				return "", fmt.Errorf("derived key %s input %s: invalid TypeScript property name %q", key.Name, input.Name, prop)
			}
			out.WriteString("  readonly ")
			out.WriteString(prop)
			if input.Optional {
				out.WriteString("?")
			}
			out.WriteString(": ")
			out.WriteString(tsInputType(input.Type))
			out.WriteString(";\n")
		}
		out.WriteString("}\n\n")

		out.WriteString("export function ")
		out.WriteString(functionName)
		out.WriteString("(input: ")
		out.WriteString(typeName)
		out.WriteString("): string {\n")
		out.WriteString("  const values: Record<string, KeyContractInputValue> = {};\n")
		for _, input := range key.Inputs {
			prop := tsPropertyName(input)
			if input.Optional {
				out.WriteString("  if (input.")
				out.WriteString(prop)
				out.WriteString(" !== undefined) values[")
				out.WriteString(quoteTS(input.Name))
				out.WriteString("] = input.")
				out.WriteString(prop)
				out.WriteString(";\n")
				continue
			}
			out.WriteString("  values[")
			out.WriteString(quoteTS(input.Name))
			out.WriteString("] = input.")
			out.WriteString(prop)
			out.WriteString(";\n")
		}
		out.WriteString("  return evaluateDerivedKey(tabletheoryModelContract, ")
		out.WriteString(quoteTS(key.Name))
		out.WriteString(", values);\n")
		out.WriteString("}\n\n")
	}

	return out.String(), nil
}

func generatedNames(key DerivedKey) (functionName string, typeName string, err error) {
	functionName = key.Helper
	if functionName == "" {
		functionName = lowerCamel(key.Name)
	}
	if !isIdentifier(functionName) {
		return "", "", fmt.Errorf("derived key %s: invalid TypeScript helper name %q", key.Name, functionName)
	}
	return functionName, upperFirst(functionName) + "Input", nil
}

func upperFirst(value string) string {
	if value == "" {
		return ""
	}
	r, size := utf8.DecodeRuneInString(value)
	if r == utf8.RuneError && size == 0 {
		return ""
	}
	return string(unicode.ToUpper(r)) + value[size:]
}

func tsPropertyName(input Input) string {
	if input.TSName != "" {
		return input.TSName
	}
	return lowerCamel(input.Name)
}

func tsInputType(inputType string) string {
	switch inputType {
	case "string":
		return "string"
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	default:
		return "KeyContractInputValue"
	}
}

func quoteTS(value string) string {
	return fmt.Sprintf("%q", value)
}

var splitNamePattern = regexp.MustCompile(`[^A-Za-z0-9]+`)

func lowerCamel(value string) string {
	parts := splitWords(value)
	if len(parts) == 0 {
		return ""
	}
	for i := range parts {
		parts[i] = strings.ToLower(parts[i])
	}
	for i := 1; i < len(parts); i++ {
		parts[i] = upperCamel(parts[i])
	}
	return strings.Join(parts, "")
}

func upperCamel(value string) string {
	parts := splitWords(value)
	if len(parts) == 0 {
		return ""
	}
	for i := range parts {
		part := strings.ToLower(parts[i])
		r, size := utf8.DecodeRuneInString(part)
		if r == utf8.RuneError && size == 0 {
			continue
		}
		parts[i] = string(unicode.ToUpper(r)) + part[size:]
	}
	return strings.Join(parts, "")
}

func splitWords(value string) []string {
	raw := splitNamePattern.Split(value, -1)
	parts := make([]string, 0, len(raw))
	for _, part := range raw {
		if part != "" {
			parts = append(parts, part)
		}
	}
	return parts
}

func isIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for i, r := range value {
		if i == 0 {
			if r != '_' && r != '$' && !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if r != '_' && r != '$' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}
